'use strict';

/**
 * SME knowledge capture: the seed question set (owner brief 2026-09-15), English and Spanish.
 * Seeding only INSERTS a section or question whose code does not exist yet; once a row is in the
 * database the admin owns its wording, order and active flag, and a redeploy never overwrites it.
 * Spanish uses usted.
 */

const SECTIONS = [
  { code: 'S01', en: 'Background and career', es: 'Trayectoria y carrera' },
  { code: 'S02', en: 'How builders decide incentives', es: 'Cómo deciden las constructoras los incentivos' },
  { code: 'S03', en: 'Quick move-in vs. to-be-built', es: 'Casa lista para mudarse vs. por construir' },
  { code: 'S04', en: 'Inside the sales office', es: 'Dentro de la oficina de ventas' },
  { code: 'S05', en: 'Agent registration and commissions', es: 'Registro de agentes y comisiones' },
  { code: 'S06', en: 'Negotiation', es: 'Negociación' },
  { code: 'S07', en: 'Financing', es: 'Financiamiento' },
  { code: 'S08', en: 'Costs after closing', es: 'Costos después del cierre' },
  { code: 'S09', en: 'Buyer mistakes and regrets', es: 'Errores y arrepentimientos de los compradores' },
  { code: 'S10', en: 'Spanish-speaking and first-time buyers', es: 'Compradores hispanohablantes y de primera vivienda' },
  { code: 'S11', en: 'Tampa Bay market today', es: 'El mercado de Tampa Bay hoy' },
  { code: 'S12', en: 'Verification (rules for BuyersLine)', es: 'Verificación (reglas para BuyersLine)' },
  { code: 'S13', en: 'For BuyersLine', es: 'Para BuyersLine' },
  { code: 'S14', en: 'Open', es: 'Preguntas abiertas' }
];

// [section, english, spanish, why-we-ask english, why-we-ask spanish]
const Q = [
  ['S01', 'How many years in real estate, and how many in new construction specifically?', '¿Cuántos años lleva en bienes raíces y cuántos específicamente en construcción nueva?', 'It tells us how much weight to give each answer and which market cycles you have lived through.', 'Nos indica cuánto peso dar a cada respuesta y qué ciclos del mercado ha vivido.'],
  ['S01', 'Which builders have you worked for or with, and in which roles?', '¿Con qué constructoras ha trabajado o colaborado, y en qué funciones?', 'Different builders run incentives and registration differently; we need to know which ones you know from the inside.', 'Cada constructora maneja incentivos y registros de forma distinta; necesitamos saber cuáles conoce por dentro.'],
  ['S01', 'Which Tampa Bay markets and communities do you know best?', '¿Qué mercados y comunidades de Tampa Bay conoce mejor?', 'We will lean on your knowledge first in the areas you know best.', 'Nos apoyaremos primero en su conocimiento en las zonas que mejor conoce.'],
  ['S01', 'What did you do before real estate, and how does it shape how you sell?', '¿A qué se dedicaba antes de los bienes raíces y cómo influye eso en su forma de vender?', 'Your approach helps us write guidance that sounds like an experienced professional, not a script.', 'Su enfoque nos ayuda a escribir orientación que suene a un profesional con experiencia, no a un guion.'],
  ['S01', 'How has new-construction selling changed from when you started to today?', '¿Cómo ha cambiado la venta de casas nuevas desde que empezó hasta hoy?', 'It helps us separate lasting rules from habits that no longer apply.', 'Nos ayuda a separar las reglas permanentes de las costumbres que ya no aplican.'],

  ['S02', 'Who decides incentives: corporate, division, or the sales manager? How often do they change?', '¿Quién decide los incentivos: la corporación, la división o el gerente de ventas? ¿Con qué frecuencia cambian?', 'It sets how often BuyersLine must re-check an offer and who can confirm it.', 'Define con qué frecuencia BuyersLine debe volver a revisar una oferta y quién puede confirmarla.'],
  ['S02', "What's the difference between the incentive on the flyer and what a buyer can actually get?", '¿Qué diferencia hay entre el incentivo del folleto y lo que un comprador realmente puede obtener?', 'Buyers compare flyers; we need to explain the gap honestly.', 'Los compradores comparan folletos; necesitamos explicar la diferencia con honestidad.'],
  ['S02', "Which incentives require the builder's affiliated lender, and what happens if the buyer uses their own lender?", '¿Qué incentivos exigen usar el prestamista afiliado de la constructora y qué pasa si el comprador usa su propio prestamista?', 'This is the most common way buyers lose an incentive without realizing it.', 'Es la forma más común en que los compradores pierden un incentivo sin darse cuenta.'],
  ['S02', 'When do incentives get better: month end, quarter end, fiscal year end, community closeout, aged spec homes?', '¿Cuándo mejoran los incentivos: a fin de mes, fin de trimestre, fin del año fiscal, cierre de una comunidad, casas terminadas que llevan tiempo sin venderse?', 'Timing advice is one of the most valuable things we can give a buyer.', 'Aconsejar sobre el momento es de lo más valioso que podemos darle a un comprador.'],
  ['S02', 'How are rate buydowns structured (2-1, 3-2-1, permanent), and what does the payment look like when the buydown ends?', '¿Cómo se estructuran las reducciones de tasa (2-1, 3-2-1, permanente) y cómo queda el pago cuando termina la reducción?', 'Every temporary buydown on BuyersLine must show the payment after it ends.', 'Toda reducción temporal en BuyersLine debe mostrar el pago después de que termina.'],
  ['S02', "What incentives can stack, and what can't?", '¿Qué incentivos se pueden combinar y cuáles no?', 'It keeps us from adding up offers a buyer can never receive together.', 'Evita que sumemos ofertas que un comprador nunca podría recibir juntas.'],
  ['S02', 'What do builders never advertise but will give if asked?', '¿Qué nunca anuncian las constructoras pero sí conceden si se lo piden?', 'It becomes the questions we teach buyers and agents to ask.', 'Se convierte en las preguntas que enseñamos a compradores y agentes a hacer.'],
  ['S02', 'How long does a written incentive quote stay valid?', '¿Cuánto tiempo sigue vigente una cotización de incentivo por escrito?', 'It sets how long a verified incentive can stay visible on BuyersLine.', 'Define cuánto tiempo puede seguir visible en BuyersLine un incentivo verificado.'],
  ['S02', 'Why do builders prefer incentives over price cuts?', '¿Por qué las constructoras prefieren dar incentivos en lugar de bajar el precio?', 'Buyers understand an offer better when they know the builder\'s reason.', 'El comprador entiende mejor una oferta cuando conoce la razón de la constructora.'],
  ['S02', 'How do incentives affect appraisals?', '¿Cómo afectan los incentivos a los avalúos?', 'Appraisal surprises can break a deal late; we want to warn buyers early.', 'Las sorpresas en el avalúo pueden romper un trato al final; queremos advertir a tiempo.'],

  ['S03', 'Which gets the better deal and why?', '¿Cuál obtiene mejor trato y por qué?', 'It helps buyers choose between a home that is ready and one still to be built.', 'Ayuda a elegir entre una casa lista y una por construir.'],
  ['S03', 'How early do you know a spec home is about to be reduced?', '¿Con cuánta anticipación se sabe que van a rebajar una casa terminada en inventario?', 'It tells us whether a buyer should wait or act now.', 'Nos indica si el comprador debe esperar o actuar ya.'],
  ['S03', 'Realistic range of hidden costs on a to-be-built: lot premium, options, design center, structural upgrades.', 'Rango realista de costos ocultos en una casa por construir: prima por lote, opciones, centro de diseño, mejoras estructurales.', 'Base prices mislead; we need honest ranges to set expectations.', 'Los precios base engañan; necesitamos rangos honestos para fijar expectativas.'],
  ['S03', 'Realistic timelines: first visit to contract, contract to close, for each type.', 'Plazos realistas: de la primera visita al contrato y del contrato al cierre, para cada tipo.', 'Timelines decide which homes fit a buyer\'s move date.', 'Los plazos deciden qué casas encajan con la fecha de mudanza del comprador.'],
  ['S03', 'What delays construction most often, and how should a buyer plan for it?', '¿Qué retrasa la construcción con más frecuencia y cómo debe planificarlo el comprador?', 'It lets us advise on leases, rate locks and moving dates.', 'Nos permite aconsejar sobre contratos de alquiler, bloqueos de tasa y fechas de mudanza.'],

  ['S04', 'Walk through exactly what happens when a buyer arrives with an agent versus without one.', 'Describa paso a paso qué pasa cuando un comprador llega con agente y cuando llega sin él.', 'Buyers need to know what the first visit will look like before they walk in.', 'El comprador necesita saber cómo será la primera visita antes de entrar.'],
  ['S04', 'What questions does the sales office ask on the first visit?', '¿Qué preguntas hace la oficina de ventas en la primera visita?', 'We can prepare buyers so they answer without giving away their position.', 'Podemos preparar al comprador para responder sin debilitar su posición.'],
  ['S04', 'What does a buyer need to bring to be taken seriously?', '¿Qué debe llevar un comprador para que lo tomen en serio?', 'It becomes a checklist in the buyer\'s report.', 'Se convierte en una lista de verificación en el informe del comprador.'],
  ['S04', 'How do sales reps qualify buyers in the first five minutes?', '¿Cómo califican los vendedores a un comprador en los primeros cinco minutos?', 'It helps us ask buyers similar questions so the handoff to the agent is useful.', 'Nos ayuda a hacer preguntas parecidas para que el traspaso al agente sea útil.'],
  ['S04', 'What is quota pressure like, and how can a buyer benefit from it?', '¿Cómo es la presión por cuotas y cómo puede aprovecharla un comprador?', 'It informs timing and negotiation advice.', 'Orienta los consejos sobre el momento y la negociación.'],
  ['S04', 'What do sales reps say to discourage buyers from using an outside agent?', '¿Qué dicen los vendedores para desanimar a los compradores de usar un agente externo?', 'Buyers should recognize these lines and know their options.', 'El comprador debe reconocer estas frases y conocer sus opciones.'],
  ['S04', 'How does the office treat a buyer who said "I have an agent" on the phone but arrives alone?', '¿Cómo trata la oficina a un comprador que dijo por teléfono "tengo agente" pero llega solo?', 'It is a common way buyers lose representation by accident.', 'Es una forma común en que los compradores pierden su representación sin querer.'],
  ['S04', 'What information does the sales office log about a buyer, and how is it used later?', '¿Qué información registra la oficina de ventas sobre el comprador y cómo la usa después?', 'Buyers deserve to know what they share on a guest card.', 'El comprador merece saber qué comparte en una tarjeta de visita.'],

  ['S05', 'The most common mistakes agents make that cost them the commission.', 'Los errores más comunes de los agentes que les cuestan la comisión.', 'These become rules our agent follows on every lead.', 'Se convierten en reglas que nuestro agente sigue con cada contacto.'],
  ['S05', 'If a buyer submits a builder website form before meeting an agent, is there any way to fix it?', 'Si un comprador llena un formulario en el sitio web de la constructora antes de conocer a un agente, ¿hay alguna forma de corregirlo?', 'Many buyers do this before they find us; we need the honest answer.', 'Muchos compradores lo hacen antes de encontrarnos; necesitamos la respuesta honesta.'],
  ['S05', 'How do VIP programs interact with agent registration?', '¿Cómo se relacionan los programas VIP con el registro del agente?', 'VIP lists can quietly block representation.', 'Las listas VIP pueden bloquear la representación sin que se note.'],
  ['S05', 'Which Tampa Bay communities are currently not paying co-op, and why?', '¿Qué comunidades de Tampa Bay no están pagando comisión compartida hoy y por qué?', 'It changes whether representation is free for the buyer in that community.', 'Cambia si la representación es gratuita para el comprador en esa comunidad.'],
  ['S05', 'How do co-op percentages get set, and when do they change?', '¿Cómo se fijan los porcentajes de comisión compartida y cuándo cambian?', 'It tells us how often to confirm them.', 'Nos indica con qué frecuencia confirmarlos.'],
  ['S05', 'What is the registration window and extension process at each builder you know?', '¿Cuál es el plazo de registro y el proceso de extensión en cada constructora que conoce?', 'These become builder-by-builder rules for our agent.', 'Se convierten en reglas por constructora para nuestro agente.'],
  ['S05', "What should an independent buyer's agent do in the first 24 hours after getting a new-construction lead?", '¿Qué debe hacer un agente independiente del comprador en las primeras 24 horas después de recibir un contacto de construcción nueva?', 'It shapes the hand-off brief and the agent\'s checklist.', 'Da forma al resumen de traspaso y a la lista de tareas del agente.'],

  ['S06', 'What can actually be negotiated: price, lot premium, options, closing costs, appliances, fence, blinds, HOA credits?', '¿Qué se puede negociar de verdad: precio, prima por lote, opciones, costos de cierre, electrodomésticos, cerca, persianas, créditos de HOA?', 'It keeps buyer advice realistic.', 'Mantiene realistas los consejos al comprador.'],
  ['S06', 'What does a buyer say that instantly weakens their position?', '¿Qué dice un comprador que debilita su posición al instante?', 'We can coach buyers to avoid it.', 'Podemos preparar al comprador para evitarlo.'],
  ['S06', 'What does a buyer say that instantly strengthens it?', '¿Qué dice un comprador que la fortalece al instante?', 'We can coach buyers to use it.', 'Podemos preparar al comprador para usarlo.'],
  ['S06', 'How do you get a sales manager involved, and when does it help?', '¿Cómo se logra que intervenga el gerente de ventas y cuándo ayuda?', 'It tells our agent when to escalate.', 'Le indica a nuestro agente cuándo escalar.'],
  ['S06', 'How does competition between builders in the same area affect offers?', '¿Cómo afecta a las ofertas la competencia entre constructoras de la misma zona?', 'It helps us compare communities fairly.', 'Nos ayuda a comparar comunidades de forma justa.'],

  ['S07', "Honest comparison of the builder's affiliated lender versus outside lenders on rate and fees.", 'Comparación honesta entre el prestamista afiliado de la constructora y los prestamistas externos en tasa y comisiones.', 'Buyers need a fair picture before choosing a lender.', 'El comprador necesita un panorama justo antes de elegir prestamista.'],
  ['S07', 'The traps in a preferred-lender incentive.', 'Las trampas de un incentivo condicionado al prestamista preferido.', 'These become warnings on incentives that require the builder\'s lender.', 'Se convierten en advertencias en los incentivos que exigen el prestamista de la constructora.'],
  ['S07', 'How often do buyers lose an incentive by switching lenders, and how do they avoid it?', '¿Con qué frecuencia pierden los compradores un incentivo al cambiar de prestamista y cómo lo evitan?', 'It prevents a costly late surprise.', 'Evita una sorpresa costosa al final.'],
  ['S07', 'What do buyers misunderstand about pre-approval versus pre-qualification?', '¿Qué malinterpretan los compradores sobre la preaprobación frente a la precalificación?', 'It shapes how Ana asks about financing.', 'Da forma a cómo pregunta Ana sobre el financiamiento.'],
  ['S07', 'What down payment and credit profiles actually get the advertised incentive?', '¿Qué pago inicial y perfil de crédito obtienen realmente el incentivo anunciado?', 'It tells us who an advertised offer really fits.', 'Nos indica a quién le sirve de verdad una oferta anunciada.'],

  ['S08', 'What buyers misunderstand about HOA, CDD fees, property taxes on new builds, and insurance.', 'Qué malinterpretan los compradores sobre la HOA, las cuotas CDD, los impuestos a la propiedad en casas nuevas y el seguro.', 'Monthly costs after closing are where buyers get surprised most.', 'Los costos mensuales después del cierre son donde más se sorprenden los compradores.'],
  ['S08', 'How the first-year tax bill differs from the estimate, and why.', 'En qué se diferencia la factura de impuestos del primer año del estimado y por qué.', 'It lets us warn buyers about the second-year payment change.', 'Nos permite advertir sobre el cambio de pago en el segundo año.'],
  ['S08', "Builder warranty: what is covered, what isn't, and how to use it.", 'Garantía de la constructora: qué cubre, qué no cubre y cómo usarla.', 'It becomes buyer education after closing.', 'Se convierte en orientación para el comprador después del cierre.'],
  ['S08', 'Common punch-list and walkthrough issues buyers miss.', 'Detalles comunes de la lista de pendientes y del recorrido final que los compradores pasan por alto.', 'It becomes a walkthrough checklist.', 'Se convierte en una lista para el recorrido final.'],

  ['S09', 'What do buyers regret most six months after closing?', '¿De qué se arrepienten más los compradores seis meses después del cierre?', 'Regrets tell us what to warn about before contract.', 'Los arrepentimientos nos dicen sobre qué advertir antes del contrato.'],
  ['S09', 'What do buyers get wrong about lot selection?', '¿En qué se equivocan los compradores al elegir el lote?', 'Lot choice is permanent; it deserves good advice.', 'La elección del lote es permanente; merece un buen consejo.'],
  ['S09', 'What do buyers get wrong about upgrades and resale?', '¿En qué se equivocan los compradores con las mejoras y la reventa?', 'It helps buyers spend where it holds value.', 'Ayuda al comprador a gastar donde conserva valor.'],
  ['S09', 'What should a buyer ask on the first visit that nobody asks?', '¿Qué debería preguntar un comprador en la primera visita que casi nadie pregunta?', 'It becomes questions in the buyer\'s report.', 'Se convierte en preguntas del informe del comprador.'],
  ['S09', 'The most common reason a new-construction deal falls through.', 'La razón más común por la que se cae un trato de construcción nueva.', 'We can flag that risk early.', 'Podemos señalar ese riesgo a tiempo.'],

  ['S10', "How Spanish-speaking buyers are treated in sales offices, and what they need that they don't get.", 'Cómo tratan a los compradores hispanohablantes en las oficinas de ventas y qué necesitan que no reciben.', 'BuyersLine serves Spanish-speaking buyers with the same quality as English.', 'BuyersLine atiende a compradores hispanohablantes con la misma calidad que en inglés.'],
  ['S10', 'Common misunderstandings that come from translation or unfamiliar US process.', 'Malentendidos comunes por la traducción o por no conocer el proceso en EE. UU.', 'It shapes how Ana explains each step in Spanish.', 'Da forma a cómo Ana explica cada paso en español.'],
  ['S10', 'What first-time buyers most need explained before visiting a community.', 'Qué necesitan que les expliquen más los compradores de primera vivienda antes de visitar una comunidad.', 'It becomes first-time buyer education.', 'Se convierte en orientación para compradores de primera vivienda.'],
  ['S10', 'Programs, credits, or assistance that first-time buyers in Florida typically miss.', 'Programas, créditos o ayudas que los compradores de primera vivienda en Florida suelen pasar por alto.', 'We can point buyers to help they qualify for.', 'Podemos orientar al comprador hacia ayudas para las que califica.'],

  ['S11', 'Which builders are most aggressive on incentives right now, and which are stingy?', '¿Qué constructoras son las más agresivas con los incentivos ahora y cuáles son tacañas?', 'It guides where our research looks first. This is kept inside BuyersLine and never quoted to buyers.', 'Orienta dónde busca primero nuestra investigación. Se queda dentro de BuyersLine y nunca se cita a los compradores.'],
  ['S11', 'Which communities are struggling to sell, and which are selling out?', '¿Qué comunidades tienen dificultad para vender y cuáles se están agotando?', 'It helps with timing and negotiation advice.', 'Ayuda con consejos sobre el momento y la negociación.'],
  ['S11', 'What do you see coming in the next six months: more incentives, price cuts, fewer starts?', '¿Qué ve venir en los próximos seis meses: más incentivos, rebajas de precio, menos construcciones nuevas?', 'It informs how we frame timing, labelled as an outlook, never a promise.', 'Orienta cómo hablamos del momento, presentado como perspectiva, nunca como promesa.'],
  ['S11', 'Which areas of Tampa Bay are best value for new construction right now, and why?', '¿Qué zonas de Tampa Bay ofrecen mejor valor en construcción nueva ahora y por qué?', 'It helps buyers compare areas on price and features, never on who lives there.', 'Ayuda a comparar zonas por precio y características, nunca por quién vive allí.'],
  ['S11', 'Which builders have quality or service problems buyers should know about?', '¿Qué constructoras tienen problemas de calidad o de servicio que los compradores deberían conocer?', 'It is for internal review only; nothing here reaches a buyer without verification.', 'Es solo para revisión interna; nada de esto llega a un comprador sin verificación.'],

  ['S12', 'Fastest reliable way to confirm an incentive is real and current without visiting.', 'La forma más rápida y confiable de confirmar que un incentivo es real y vigente sin visitar.', 'It becomes the verification procedure for our licensed agent.', 'Se convierte en el procedimiento de verificación de nuestro agente con licencia.'],
  ['S12', 'Who in a sales office actually knows the current offer, and how to reach them.', 'Quién en una oficina de ventas conoce de verdad la oferta actual y cómo contactarlo.', 'It tells our agent who to call.', 'Le indica a nuestro agente a quién llamar.'],
  ['S12', 'How should a "verified with date" system work so it stays honest? What expiry window?', '¿Cómo debería funcionar un sistema de "verificado con fecha" para que siga siendo honesto? ¿Qué plazo de vencimiento?', 'It sets how long a verified incentive stays visible.', 'Define cuánto tiempo sigue visible un incentivo verificado.'],
  ['S12', 'What details must a verified incentive record include to be useful?', '¿Qué datos debe incluir el registro de un incentivo verificado para ser útil?', 'It shapes the verification form.', 'Da forma al formulario de verificación.'],
  ['S12', 'How to spot an incentive that is technically true but practically unreachable.', 'Cómo detectar un incentivo que es cierto en teoría pero inalcanzable en la práctica.', 'We never want to show a buyer an offer they cannot get.', 'Nunca queremos mostrarle a un comprador una oferta que no puede obtener.'],

  ['S13', 'If you were a buyer, what would make you trust a site like this?', 'Si usted fuera comprador, ¿qué le haría confiar en un sitio como este?', 'Trust decides whether buyers finish the report.', 'La confianza decide si el comprador termina el informe.'],
  ['S13', "If you were an independent buyer's agent, what would make you want these leads?", 'Si usted fuera un agente independiente del comprador, ¿qué le haría querer estos contactos?', 'It shapes what the agent receives with each lead.', 'Da forma a lo que recibe el agente con cada contacto.'],
  ['S13', 'Which independent agents in Tampa Bay do you respect on new construction?', '¿Qué agentes independientes de Tampa Bay respeta en construcción nueva?', 'For internal planning only; names are never shown to buyers.', 'Solo para planificación interna; los nombres nunca se muestran a los compradores.'],
  ['S13', 'What would make a builder sales office dislike this platform, and how do we avoid that?', '¿Qué haría que una oficina de ventas de una constructora rechazara esta plataforma y cómo lo evitamos?', 'We want to work with builders, not against them.', 'Queremos trabajar con las constructoras, no en su contra.'],
  ['S13', 'What is the one thing about builder sales nobody on the buyer side understands?', '¿Qué es lo único sobre las ventas de las constructoras que nadie del lado del comprador entiende?', 'It may be the most useful thing we teach buyers.', 'Puede ser lo más útil que le enseñemos al comprador.'],
  ['S13', 'What questions should Ana ask a buyer to know if they are serious?', '¿Qué preguntas debería hacerle Ana a un comprador para saber si va en serio?', 'It shapes Ana\'s questions and the readiness score.', 'Da forma a las preguntas de Ana y a la puntuación de preparación.'],
  ['S13', 'What should Ana never say to a buyer?', '¿Qué nunca debería decirle Ana a un comprador?', 'It becomes a hard rule for Ana.', 'Se convierte en una regla estricta para Ana.'],

  ['S14', "Anything I didn't ask that a buyer should know.", 'Cualquier cosa que no le pregunté y que un comprador debería saber.', 'Your experience may cover what we did not think to ask.', 'Su experiencia puede cubrir lo que no se nos ocurrió preguntar.'],
  ['S14', "Anything I didn't ask that an agent should know.", 'Cualquier cosa que no le pregunté y que un agente debería saber.', 'Your experience may cover what we did not think to ask.', 'Su experiencia puede cubrir lo que no se nos ocurrió preguntar.'],
  ['S14', 'Stories: three deals that taught you the most, and what happened.', 'Historias: tres tratos que más le enseñaron y qué pasó.', 'Real stories make buyer education clear and memorable. Names are removed before anything is used.', 'Las historias reales hacen la orientación clara y fácil de recordar. Se quitan los nombres antes de usar cualquier cosa.']
];

const QUESTIONS = Q.map((q, i) => ({
  code: 'Q' + String(i + 1).padStart(2, '0'), section: q[0], en: q[1], es: q[2], help_en: q[3], help_es: q[4],
  answer_type: 'long_text', sort_order: i + 1
}));

module.exports = { SECTIONS, QUESTIONS };
