import React, { useState, useEffect } from 'react';
import api from '../services/api';
export default function DocumentVault() {
  const [docs, setDocs] = useState([]);
  const [filter, setFilter] = useState({doc_type:'',load_id:''});
  const [uf, setUf] = useState({doc_type:'bol',load_id:'',filename:''});
  const [show, setShow] = useState(false);
  useEffect(()=>{loadD();}, []);
  const loadD = async () => { const p = new URLSearchParams(); if(filter.doc_type) p.set('doc_type',filter.doc_type); if(filter.load_id) p.set('load_id',filter.load_id); const {data}=await api.get(`/documents?${p}`).catch(()=>({data:{data:[]}})); setDocs(data?.data||[]); };
  const upload = async (e) => { e.preventDefault(); try { await api.post('/documents/upload',uf); alert('Uploaded!'); setShow(false); loadD(); } catch(e){alert(e.response?.data?.error||'Failed');} };
  const verify = async (id) => { try { const {data}=await api.get(`/documents/load/${id}/verify`); const r=data.data; alert(`Load #${id}: ${r.billing_ready?'READY for billing':'Missing: '+r.missing_documents.join(', ')}`); } catch(e){alert('Failed');} };
  const dc = {bol:'#0EA5E9',pod:'#10B981',rate_confirmation:'#F59E0B',insurance_cert:'#A855F7',w9:'#EF4444',carrier_agreement:'#EC4899',invoice:'#F97316',other:'#6B7280'};
  return (<div>
    <h1 style={S.title}>DOCUMENT VAULT</h1>
    <div style={S.bar}><select style={S.fi} value={filter.doc_type} onChange={e=>setFilter({...filter,doc_type:e.target.value})}><option value="">All Types</option><option value="bol">BOL</option><option value="pod">POD</option><option value="rate_confirmation">Rate Conf</option><option value="insurance_cert">Insurance</option><option value="w9">W-9</option><option value="carrier_agreement">Agreement</option></select><input style={S.fi} placeholder="Load ID" value={filter.load_id} onChange={e=>setFilter({...filter,load_id:e.target.value})} /><button style={S.fb} onClick={loadD}>Filter</button><button style={S.ub} onClick={()=>setShow(!show)}>+ Upload</button>{filter.load_id&&<button style={S.vb} onClick={()=>verify(filter.load_id)}>Verify Complete</button>}</div>
    {show&&<div style={S.fc}><form onSubmit={upload} style={{display:'flex',gap:10,flexWrap:'wrap',alignItems:'center'}}><select style={S.input} value={uf.doc_type} onChange={e=>setUf({...uf,doc_type:e.target.value})}><option value="bol">BOL</option><option value="pod">POD</option><option value="rate_confirmation">Rate Conf</option><option value="insurance_cert">Insurance</option><option value="w9">W-9</option><option value="carrier_agreement">Agreement</option><option value="other">Other</option></select><input style={S.input} placeholder="Load ID" value={uf.load_id} onChange={e=>setUf({...uf,load_id:e.target.value})} /><input style={S.input} placeholder="Filename" value={uf.filename} onChange={e=>setUf({...uf,filename:e.target.value})} required /><button style={S.btn} type="submit">Upload</button></form></div>}
    <div style={S.tw}><table style={S.table}><thead><tr><th style={S.th}>ID</th><th style={S.th}>TYPE</th><th style={S.th}>FILENAME</th><th style={S.th}>LOAD</th><th style={S.th}>UPLOADED BY</th><th style={S.th}>DATE</th></tr></thead><tbody>{docs.map(d=>(<tr key={d.id} style={S.tr}><td style={S.td}>#{d.id}</td><td style={S.td}><span style={{padding:'3px 8px',borderRadius:10,fontSize:10,fontWeight:600,textTransform:'uppercase',background:(dc[d.doc_type]||'#8B949E')+'22',color:dc[d.doc_type]||'#8B949E'}}>{d.doc_type}</span></td><td style={S.td}>{d.original_name||d.filename}</td><td style={S.td}>{d.load_id||'-'}</td><td style={S.td}>{d.uploaded_by_name||'-'}</td><td style={S.td}>{new Date(d.created_at).toLocaleDateString()}</td></tr>))}{docs.length===0&&<tr><td colSpan={6} style={{...S.td,textAlign:'center',color:'#8B949E'}}>No documents</td></tr>}</tbody></table></div>
  </div>);
}
const S={title:{fontFamily:"'Bebas Neue',sans-serif",fontSize:28,color:'#0EA5E9',letterSpacing:2,marginBottom:16},bar:{display:'flex',gap:8,marginBottom:16,flexWrap:'wrap',alignItems:'center'},fi:{padding:'8px 12px',background:'#161B22',border:'1px solid #30363D',borderRadius:6,color:'#E6EDF3',fontSize:13,outline:'none'},fb:{padding:'8px 16px',background:'#30363D',color:'#E6EDF3',border:'none',borderRadius:6,fontSize:13,cursor:'pointer'},ub:{padding:'8px 16px',background:'#0EA5E9',color:'#fff',border:'none',borderRadius:6,fontSize:13,cursor:'pointer',fontWeight:600},vb:{padding:'8px 16px',background:'#10B981',color:'#fff',border:'none',borderRadius:6,fontSize:13,cursor:'pointer',fontWeight:600},fc:{background:'#161B22',border:'1px solid #21262D',borderRadius:10,padding:20,marginBottom:16},input:{padding:'8px 12px',background:'#0D1117',border:'1px solid #30363D',borderRadius:6,color:'#E6EDF3',fontSize:13,outline:'none',minWidth:150},btn:{padding:'8px 16px',background:'#0EA5E9',color:'#fff',border:'none',borderRadius:6,fontSize:13,fontWeight:600,cursor:'pointer'},tw:{background:'#161B22',border:'1px solid #21262D',borderRadius:10,overflow:'auto'},table:{width:'100%',borderCollapse:'collapse',minWidth:600},th:{padding:'12px 14px',textAlign:'left',fontSize:11,color:'#8B949E',fontWeight:600,letterSpacing:1,borderBottom:'1px solid #21262D'},tr:{borderBottom:'1px solid #21262D'},td:{padding:'10px 14px',fontSize:13}};
