import React, { useState, useEffect } from 'react';
import api from '../services/api';
export default function FreightMatching() {
  const [lid, setLid] = useState('');
  const [matches, setMatches] = useState(null);
  const [campaigns, setCampaigns] = useState([]);
  const [loading, setLoading] = useState(false);
  useEffect(()=>{loadC();}, []);
  const loadC = async () => { const {data}=await api.get('/matching/campaigns').catch(()=>({data:{data:[]}})); setCampaigns(data?.data||[]); };
  const normId = (id) => /^\d+$/.test(id) ? `CW-${id}` : id;
  const run = async () => { if(!lid) return; setLoading(true); try { const {data}=await api.post(`/matching/match/${normId(lid)}`); setMatches(data.data); } catch(e){alert(e.response?.data?.error||'Failed');} setLoading(false); };
  const launch = async () => { if(!lid) return; try { const {data}=await api.post(`/matching/campaign/${normId(lid)}`,{max_carriers:10}); alert(data.data.message); loadC(); } catch(e){alert(e.response?.data?.error||'Failed');} };
  const sc = s => s>=70?'#10B981':s>=40?'#F59E0B':'#EF4444';
  return (<div>
    <h1 style={S.title}>AI FREIGHT MATCHING</h1>
    <div style={S.cc}><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><input style={S.input} type="text" placeholder="Load Ref (e.g. 417238)" value={lid} onChange={e=>setLid(e.target.value)} /><button style={S.btn} onClick={run} disabled={loading}>{loading?'Matching...':'Find Best Carriers'}</button><button style={S.cb} onClick={launch} disabled={!matches}>Launch Campaign</button></div></div>
    {matches&&<div style={{marginBottom:24}}><h2 style={{fontFamily:"'Bebas Neue',sans-serif",fontSize:18,marginBottom:12}}>MATCHES: {matches.load_ref} — {matches.lane} <span style={{fontSize:12,color:'#8B949E',fontWeight:400}}>({matches.top_matches} of {matches.total_carriers_evaluated})</span></h2><div style={S.tw}><table style={S.table}><thead><tr><th style={S.th}>#</th><th style={S.th}>CARRIER</th><th style={S.th}>SCORE</th><th style={S.th}>LANE</th><th style={S.th}>RATE</th><th style={S.th}>RELIABILITY</th><th style={S.th}>SAFETY</th><th style={S.th}>PHONE</th></tr></thead><tbody>{matches.matches.map((m,i)=>(<tr key={m.carrier_id} style={S.tr}><td style={S.td}><strong>#{i+1}</strong></td><td style={S.td}><div style={{fontWeight:600}}>{m.company_name||m.full_name}</div><div style={{fontSize:11,color:'#8B949E'}}>{m.email}</div></td><td style={S.td}><span style={{padding:'4px 10px',borderRadius:8,fontSize:14,fontWeight:700,background:sc(m.match_score)+'22',color:sc(m.match_score)}}>{m.match_score}</span></td><td style={S.td}>{m.scores.lane}</td><td style={S.td}>{m.scores.rate}</td><td style={S.td}>{m.scores.reliability}</td><td style={S.td}>{m.scores.safety}</td><td style={S.td}>{m.phone||'-'}</td></tr>))}</tbody></table></div></div>}
    <h2 style={{fontFamily:"'Bebas Neue',sans-serif",fontSize:20,marginBottom:12}}>CAMPAIGNS</h2>
    <div style={S.tw}><table style={S.table}><thead><tr><th style={S.th}>ID</th><th style={S.th}>LOAD</th><th style={S.th}>CARRIERS</th><th style={S.th}>BOOKED</th><th style={S.th}>INTERESTED</th><th style={S.th}>DECLINED</th></tr></thead><tbody>{campaigns.map(c=>(<tr key={c.campaign_id} style={S.tr}><td style={S.td}><strong>{c.campaign_id}</strong></td><td style={S.td}>#{c.load_id}</td><td style={S.td}>{c.total_carriers}</td><td style={{...S.td,color:'#10B981'}}>{c.booked||0}</td><td style={{...S.td,color:'#F59E0B'}}>{c.interested||0}</td><td style={{...S.td,color:'#EF4444'}}>{c.declined||0}</td></tr>))}{campaigns.length===0&&<tr><td colSpan={6} style={{...S.td,textAlign:'center',color:'#8B949E'}}>No campaigns</td></tr>}</tbody></table></div>
  </div>);
}
const S={title:{fontFamily:"'Bebas Neue',sans-serif",fontSize:28,color:'#0EA5E9',letterSpacing:2,marginBottom:16},cc:{background:'#161B22',border:'1px solid #21262D',borderRadius:10,padding:20,marginBottom:20},input:{padding:'10px 14px',background:'#0D1117',border:'1px solid #30363D',borderRadius:6,color:'#E6EDF3',fontSize:14,outline:'none',minWidth:150},btn:{padding:'10px 20px',background:'#0EA5E9',color:'#fff',border:'none',borderRadius:6,fontSize:14,fontWeight:600,cursor:'pointer'},cb:{padding:'10px 20px',background:'#A855F7',color:'#fff',border:'none',borderRadius:6,fontSize:14,fontWeight:600,cursor:'pointer'},tw:{background:'#161B22',border:'1px solid #21262D',borderRadius:10,overflow:'auto'},table:{width:'100%',borderCollapse:'collapse',minWidth:600},th:{padding:'12px 14px',textAlign:'left',fontSize:11,color:'#8B949E',fontWeight:600,letterSpacing:1,borderBottom:'1px solid #21262D'},tr:{borderBottom:'1px solid #21262D'},td:{padding:'10px 14px',fontSize:13}};
