'use strict';

/**
 * Filipino-Spanish Cognate Starter Set — 520+ documented loan words
 *
 * The Philippines was a Spanish colony for 333 years (1565-1898). Tagalog and
 * other Philippine languages absorbed 4,000+ Spanish loanwords. This starter
 * set covers the most common, pedagogically useful pairs for A1-B1 learners.
 *
 * Format: [word_es, word_tl, category, cefr_level, etymology_note]
 *
 * Categories: numbers, days_months, colors, family, food, kitchen, body,
 * clothing, house, school, work, time, places, transport, religion, animals,
 * nature, emotions, verbs, adjectives, objects, music_art, greetings
 *
 * Notes on orthography: Tagalog cognates often reflect Spanish pronunciation
 * using Filipino phonetics (c/qu -> k, ll -> ly, v -> b, f -> p, j -> h).
 * Example: "mantequilla" -> "mantikilya", "ventana" -> "bintana".
 */

const COGNATES = [
  // ===== NUMBERS (30) =====
  ['uno', 'uno', 'numbers', 'A1', 'Used in counting, time, money. Tagalog "isa" is native.'],
  ['dos', 'dos', 'numbers', 'A1', null],
  ['tres', 'tres', 'numbers', 'A1', null],
  ['cuatro', 'kwatro', 'numbers', 'A1', null],
  ['cinco', 'singko', 'numbers', 'A1', null],
  ['seis', 'sais', 'numbers', 'A1', null],
  ['siete', 'siyete', 'numbers', 'A1', null],
  ['ocho', 'otso', 'numbers', 'A1', null],
  ['nueve', 'nwebe', 'numbers', 'A1', null],
  ['diez', 'dyes', 'numbers', 'A1', null],
  ['once', 'onse', 'numbers', 'A1', null],
  ['doce', 'dose', 'numbers', 'A1', null],
  ['trece', 'trese', 'numbers', 'A1', null],
  ['catorce', 'katorse', 'numbers', 'A1', null],
  ['quince', 'kinse', 'numbers', 'A1', null],
  ['dieciséis', 'disisais', 'numbers', 'A1', null],
  ['diecisiete', 'disisyete', 'numbers', 'A1', null],
  ['dieciocho', 'disiotso', 'numbers', 'A1', null],
  ['diecinueve', 'disinwebe', 'numbers', 'A1', null],
  ['veinte', 'bente', 'numbers', 'A1', null],
  ['treinta', 'trenta', 'numbers', 'A1', null],
  ['cuarenta', 'kwarenta', 'numbers', 'A1', null],
  ['cincuenta', 'singkwenta', 'numbers', 'A1', null],
  ['sesenta', 'sisenta', 'numbers', 'A1', null],
  ['setenta', 'sitenta', 'numbers', 'A1', null],
  ['ochenta', 'otsenta', 'numbers', 'A1', null],
  ['noventa', 'nobenta', 'numbers', 'A1', null],
  ['ciento', 'syento', 'numbers', 'A1', null],
  ['mil', 'mil', 'numbers', 'A1', null],
  ['millón', 'milyon', 'numbers', 'A2', null],

  // ===== DAYS & MONTHS (19) =====
  ['lunes', 'lunes', 'days_months', 'A1', null],
  ['martes', 'martes', 'days_months', 'A1', null],
  ['miércoles', 'miyerkules', 'days_months', 'A1', null],
  ['jueves', 'huwebes', 'days_months', 'A1', null],
  ['viernes', 'biyernes', 'days_months', 'A1', null],
  ['sábado', 'sabado', 'days_months', 'A1', null],
  ['domingo', 'linggo', 'days_months', 'A1', 'Domingo -> dominggo -> linggo. Also means "week".'],
  ['enero', 'enero', 'days_months', 'A1', null],
  ['febrero', 'pebrero', 'days_months', 'A1', null],
  ['marzo', 'marso', 'days_months', 'A1', null],
  ['abril', 'abril', 'days_months', 'A1', null],
  ['mayo', 'mayo', 'days_months', 'A1', null],
  ['junio', 'hunyo', 'days_months', 'A1', null],
  ['julio', 'hulyo', 'days_months', 'A1', null],
  ['agosto', 'agosto', 'days_months', 'A1', null],
  ['septiembre', 'setyembre', 'days_months', 'A1', null],
  ['octubre', 'oktubre', 'days_months', 'A1', null],
  ['noviembre', 'nobyembre', 'days_months', 'A1', null],
  ['diciembre', 'disyembre', 'days_months', 'A1', null],

  // ===== COLORS (14) =====
  ['azul', 'asul', 'colors', 'A1', null],
  ['verde', 'berde', 'colors', 'A1', null],
  ['rosa', 'rosas', 'colors', 'A1', null],
  ['rojo', 'rohas', 'colors', 'A2', null],
  ['morado', 'morado', 'colors', 'A2', null],
  ['café', 'kape', 'colors', 'A1', 'Also means coffee.'],
  ['blanco', 'blanko', 'colors', 'A1', null],
  ['negro', 'negro', 'colors', 'A1', null],
  ['dorado', 'dorado', 'colors', 'B1', null],
  ['plateado', 'pilak', 'colors', 'B1', null],
  ['naranja', 'naranha', 'colors', 'A2', 'Also the fruit.'],
  ['color', 'kolor', 'colors', 'A1', null],
  ['granate', 'granate', 'colors', 'B1', null],
  ['amarillo', 'amaril', 'colors', 'A2', null],

  // ===== FAMILY (25) =====
  ['padre', 'padre', 'family', 'A1', 'Also "tatay" (native).'],
  ['madre', 'madre', 'family', 'A1', 'Also "nanay" (native).'],
  ['tatay', 'tatay', 'family', 'A1', 'From Spanish "tata".'],
  ['nanay', 'nanay', 'family', 'A1', 'From Spanish "nana".'],
  ['tío', 'tiyo', 'family', 'A1', null],
  ['tía', 'tiya', 'family', 'A1', null],
  ['tito', 'tito', 'family', 'A1', 'Diminutive of tío.'],
  ['tita', 'tita', 'family', 'A1', 'Diminutive of tía.'],
  ['abuelo', 'lolo', 'family', 'A1', 'abuelo -> abueloló -> lolo'],
  ['abuela', 'lola', 'family', 'A1', 'abuela -> abuelolá -> lola'],
  ['familia', 'pamilya', 'family', 'A1', null],
  ['primo', 'primo', 'family', 'A1', null],
  ['prima', 'prima', 'family', 'A1', null],
  ['hermano', 'ermano', 'family', 'A2', null],
  ['hermana', 'ermana', 'family', 'A2', null],
  ['esposo', 'esposo', 'family', 'A2', null],
  ['esposa', 'esposa', 'family', 'A2', null],
  ['compadre', 'kumpadre', 'family', 'B1', 'Godparent relationship (fellow godparent).'],
  ['comadre', 'kumare', 'family', 'B1', null],
  ['padrino', 'ninong', 'family', 'A2', 'Godfather.'],
  ['madrina', 'ninang', 'family', 'A2', 'Godmother.'],
  ['viudo', 'biyudo', 'family', 'B1', null],
  ['viuda', 'biyuda', 'family', 'B1', null],
  ['soltero', 'soltero', 'family', 'A2', null],
  ['soltera', 'soltera', 'family', 'A2', null],

  // ===== FOOD & DRINK (60) =====
  ['azúcar', 'asukal', 'food', 'A1', null],
  ['harina', 'arina', 'food', 'A2', null],
  ['queso', 'keso', 'food', 'A1', null],
  ['leche', 'letse', 'food', 'A1', null],
  ['mantequilla', 'mantikilya', 'food', 'A2', null],
  ['aceite', 'aseyte', 'food', 'A2', null],
  ['canela', 'kanela', 'food', 'B1', null],
  ['cebolla', 'sibuyas', 'food', 'A1', null],
  ['calabaza', 'kalabasa', 'food', 'A2', null],
  ['manzana', 'mansanas', 'food', 'A1', null],
  ['melón', 'melon', 'food', 'A1', null],
  ['piña', 'pinya', 'food', 'A1', null],
  ['uvas', 'ubas', 'food', 'A1', null],
  ['pan', 'pan', 'food', 'A1', 'Native "tinapay" also used.'],
  ['pan de sal', 'pandesal', 'food', 'A1', 'Filipino breakfast bread.'],
  ['sopa', 'sopa', 'food', 'A1', null],
  ['sorbete', 'sorbetes', 'food', 'A1', 'Ice cream.'],
  ['chocolate', 'tsokolate', 'food', 'A1', null],
  ['café', 'kape', 'food', 'A1', null],
  ['bizcocho', 'biskotso', 'food', 'A2', null],
  ['carne', 'karne', 'food', 'A1', null],
  ['lechón', 'litson', 'food', 'A1', 'Roasted whole pig, iconic Filipino dish.'],
  ['bistec', 'bistek', 'food', 'A2', 'Filipino beef dish.'],
  ['chorizo', 'tsoriso', 'food', 'A2', null],
  ['jamón', 'hamon', 'food', 'A1', null],
  ['tocino', 'tosino', 'food', 'A1', 'Sweet cured pork, Filipino breakfast staple.'],
  ['adobo', 'adobo', 'food', 'A1', 'Most iconic Filipino dish.'],
  ['fritada', 'apritada', 'food', 'A2', 'Filipino chicken stew.'],
  ['caldereta', 'kaldereta', 'food', 'A2', 'Filipino goat/beef stew.'],
  ['menudo', 'menudo', 'food', 'A2', null],
  ['puchero', 'putsero', 'food', 'A2', null],
  ['embutido', 'embutido', 'food', 'B1', 'Filipino meatloaf.'],
  ['morcón', 'morkon', 'food', 'B1', null],
  ['empanada', 'empanada', 'food', 'A2', null],
  ['torta', 'torta', 'food', 'A2', null],
  ['ensalada', 'insalada', 'food', 'A1', null],
  ['arroz', 'aros', 'food', 'A1', 'Native "bigas"/"kanin" more common.'],
  ['tomate', 'kamatis', 'food', 'A1', 'Via Mexican Spanish.'],
  ['ajo', 'bawang', 'food', 'A1', null],
  ['patata', 'patatas', 'food', 'A1', null],
  ['zanahoria', 'sanaorya', 'food', 'A2', null],
  ['lechuga', 'litsugas', 'food', 'A2', null],
  ['mostaza', 'mustasa', 'food', 'A2', null],
  ['vinagre', 'suka', 'food', 'A1', 'Suka is native; binagre also used.'],
  ['sal', 'asin', 'food', 'A1', 'Asin is native Austronesian.'],
  ['pimienta', 'pamintá', 'food', 'A2', null],
  ['limón', 'kalamansi', 'food', 'A1', 'Also "limon" used directly.'],
  ['plátano', 'platano', 'food', 'A1', 'Type of banana.'],
  ['mango', 'mangga', 'food', 'A1', null],
  ['sardina', 'sardinas', 'food', 'A2', null],
  ['atún', 'tuna', 'food', 'A1', null],
  ['galleta', 'galyetas', 'food', 'A1', null],
  ['yogur', 'yogurt', 'food', 'A2', null],
  ['mermelada', 'mermelada', 'food', 'B1', null],
  ['caramelo', 'karamelo', 'food', 'A2', null],
  ['dulce', 'dulse', 'food', 'A2', null],
  ['miel', 'pulot', 'food', 'B1', 'Pulot is native; miel rare.'],
  ['huevo', 'itlog', 'food', 'A1', 'Itlog is native.'],
  ['pollo', 'manok', 'food', 'A1', 'Manok is native; pollo rare.'],
  ['sardina', 'sardinas', 'food', 'A2', null],
  ['atún', 'atun', 'food', 'A2', null],

  // ===== KITCHEN & EATING (25) =====
  ['cuchara', 'kutsara', 'kitchen', 'A1', null],
  ['cuchillo', 'kutsilyo', 'kitchen', 'A1', null],
  ['tenedor', 'tinidor', 'kitchen', 'A1', null],
  ['plato', 'plato', 'kitchen', 'A1', null],
  ['vaso', 'baso', 'kitchen', 'A1', null],
  ['taza', 'tasa', 'kitchen', 'A1', null],
  ['mantel', 'mantel', 'kitchen', 'B1', null],
  ['servilleta', 'serbilyeta', 'kitchen', 'A2', null],
  ['bandeja', 'bandeha', 'kitchen', 'B1', null],
  ['caldero', 'kaldero', 'kitchen', 'A2', null],
  ['cacerola', 'kaserola', 'kitchen', 'B1', null],
  ['sartén', 'sartin', 'kitchen', 'A2', null],
  ['olla', 'olya', 'kitchen', 'A2', null],
  ['lata', 'lata', 'kitchen', 'A1', null],
  ['botella', 'botelya', 'kitchen', 'A1', null],
  ['bote', 'bote', 'kitchen', 'A1', null],
  ['caja', 'kaha', 'kitchen', 'A1', null],
  ['cajón', 'kahon', 'kitchen', 'A2', 'Also "drawer".'],
  ['jarra', 'pitsel', 'kitchen', 'A2', 'Pitsel from "pichel".'],
  ['tijeras', 'gunting', 'kitchen', 'A2', 'Gunting native; tiheras also used.'],
  ['horno', 'hurno', 'kitchen', 'B1', null],
  ['gas', 'gas', 'kitchen', 'A1', null],
  ['cocina', 'kusina', 'kitchen', 'A1', 'Also the room "kitchen".'],
  ['nevera', 'repridyerator', 'kitchen', 'A2', 'English via Spanish refrigerador.'],
  ['estufa', 'estupa', 'kitchen', 'B1', null],

  // ===== BODY PARTS (25) =====
  ['cabeza', 'kabeza', 'body', 'A1', 'Native "ulo" more common.'],
  ['brazo', 'braso', 'body', 'A1', null],
  ['mano', 'mano', 'body', 'A1', 'Native "kamay" also used.'],
  ['dedo', 'daliri', 'body', 'A2', 'Daliri native; dedo in some contexts.'],
  ['pie', 'paa', 'body', 'A1', 'Paa native.'],
  ['pierna', 'pierna', 'body', 'A2', null],
  ['rodilla', 'rodilya', 'body', 'A2', null],
  ['hombro', 'balikat', 'body', 'A2', 'Balikat native.'],
  ['boca', 'boka', 'body', 'A1', 'Native "bibig" common.'],
  ['diente', 'dyente', 'body', 'A1', 'Native "ngipin" common.'],
  ['lengua', 'dila', 'body', 'A1', 'Dila native.'],
  ['labio', 'labi', 'body', 'A2', null],
  ['nariz', 'ilong', 'body', 'A1', 'Ilong native.'],
  ['oreja', 'tainga', 'body', 'A1', 'Tainga native.'],
  ['ojo', 'mata', 'body', 'A1', 'Mata native.'],
  ['cuello', 'leeg', 'body', 'A2', 'Leeg native.'],
  ['pecho', 'dibdib', 'body', 'A2', 'Dibdib native.'],
  ['estómago', 'tiyan', 'body', 'A2', 'Tiyan native.'],
  ['espalda', 'likod', 'body', 'A2', 'Likod native.'],
  ['cabello', 'buhok', 'body', 'A1', 'Buhok native.'],
  ['cara', 'mukha', 'body', 'A1', 'Mukha native.'],
  ['corazón', 'puso', 'body', 'A2', 'Puso native.'],
  ['hueso', 'buto', 'body', 'A2', 'Buto native.'],
  ['piel', 'balat', 'body', 'A2', 'Balat native.'],
  ['sangre', 'dugo', 'body', 'A2', 'Dugo native.'],

  // ===== CLOTHING (25) =====
  ['camisa', 'kamisa', 'clothing', 'A1', null],
  ['camiseta', 'kamiseta', 'clothing', 'A1', null],
  ['pantalón', 'pantalon', 'clothing', 'A1', null],
  ['zapato', 'sapatos', 'clothing', 'A1', null],
  ['medias', 'medyas', 'clothing', 'A1', 'Socks.'],
  ['sombrero', 'sombrero', 'clothing', 'A1', null],
  ['guantes', 'gwantes', 'clothing', 'A2', null],
  ['reloj', 'relo', 'clothing', 'A1', null],
  ['corbata', 'kurbata', 'clothing', 'A2', null],
  ['blusa', 'blusa', 'clothing', 'A1', null],
  ['saya', 'saya', 'clothing', 'A1', 'Skirt.'],
  ['vestido', 'bistida', 'clothing', 'A2', null],
  ['chaqueta', 'dyaket', 'clothing', 'A2', 'Via English "jacket".'],
  ['abrigo', 'abrigo', 'clothing', 'B1', null],
  ['cinturón', 'sinturon', 'clothing', 'A2', null],
  ['bolsillo', 'bulsa', 'clothing', 'A2', null],
  ['botón', 'butones', 'clothing', 'A2', null],
  ['cierre', 'siper', 'clothing', 'A2', 'Via English "zipper".'],
  ['pañuelo', 'panyolito', 'clothing', 'A2', null],
  ['bota', 'bota', 'clothing', 'A2', null],
  ['pantufla', 'tsinelas', 'clothing', 'A1', 'From "chinelas".'],
  ['uniforme', 'uniporme', 'clothing', 'A2', null],
  ['ropa', 'damit', 'clothing', 'A1', 'Damit native.'],
  ['falda', 'palda', 'clothing', 'A2', null],
  ['anillo', 'singsing', 'clothing', 'A2', 'Singsing native; anilyo also used.'],

  // ===== HOUSE & FURNITURE (30) =====
  ['casa', 'bahay', 'house', 'A1', 'Bahay native. "Kasa" rare.'],
  ['cocina', 'kusina', 'house', 'A1', null],
  ['baño', 'banyo', 'house', 'A1', null],
  ['sala', 'sala', 'house', 'A1', 'Living room.'],
  ['cuarto', 'kwarto', 'house', 'A1', 'Bedroom.'],
  ['comedor', 'komedor', 'house', 'A2', null],
  ['ventana', 'bintana', 'house', 'A1', null],
  ['puerta', 'pinto', 'house', 'A1', null],
  ['techo', 'bubong', 'house', 'A2', 'Bubong native.'],
  ['piso', 'sahig', 'house', 'A2', 'Sahig native; piso = floor of building.'],
  ['pared', 'dingding', 'house', 'A2', 'Dingding native.'],
  ['mesa', 'mesa', 'house', 'A1', null],
  ['silla', 'silya', 'house', 'A1', null],
  ['sofá', 'sopa', 'house', 'A1', null],
  ['cama', 'kama', 'house', 'A1', null],
  ['almohada', 'unan', 'house', 'A2', 'Unan native.'],
  ['sábana', 'kumot', 'house', 'A2', 'Kumot native; sabana also used.'],
  ['armario', 'aparador', 'house', 'A2', 'From "aparador" (display cabinet).'],
  ['espejo', 'salamin', 'house', 'A2', 'Salamin native; espeho rare.'],
  ['lámpara', 'lampara', 'house', 'A1', null],
  ['bombilla', 'bumbilya', 'house', 'A2', null],
  ['corriente', 'kuryente', 'house', 'A2', 'Electricity.'],
  ['electricidad', 'elektrisidad', 'house', 'B1', null],
  ['televisión', 'telebisyon', 'house', 'A1', null],
  ['radio', 'radyo', 'house', 'A1', null],
  ['teléfono', 'telepono', 'house', 'A1', null],
  ['reloj de pared', 'orasan', 'house', 'A2', 'Orasan from "hora".'],
  ['jardín', 'hardin', 'house', 'A2', null],
  ['patio', 'bakuran', 'house', 'A2', 'Bakuran native; patio used in formal.'],
  ['garaje', 'garahe', 'house', 'A2', null],

  // ===== SCHOOL & EDUCATION (20) =====
  ['escuela', 'eskwelahan', 'school', 'A1', null],
  ['maestro', 'maestro', 'school', 'A1', null],
  ['maestra', 'maestra', 'school', 'A1', null],
  ['estudiante', 'estudyante', 'school', 'A1', null],
  ['libro', 'libro', 'school', 'A1', null],
  ['papel', 'papel', 'school', 'A1', null],
  ['lápiz', 'lapis', 'school', 'A1', null],
  ['pluma', 'pluma', 'school', 'A2', null],
  ['cuaderno', 'kwaderno', 'school', 'A1', null],
  ['examen', 'eksamen', 'school', 'A2', null],
  ['lección', 'leksyon', 'school', 'A2', null],
  ['clase', 'klase', 'school', 'A1', null],
  ['grado', 'grado', 'school', 'A2', null],
  ['número', 'numero', 'school', 'A1', null],
  ['letra', 'letra', 'school', 'A1', null],
  ['palabra', 'palabra', 'school', 'A2', null],
  ['diccionario', 'diksyonaryo', 'school', 'A2', null],
  ['universidad', 'unibersidad', 'school', 'A2', null],
  ['biblioteca', 'bibliyoteka', 'school', 'B1', null],
  ['oficina', 'opisina', 'school', 'A2', null],

  // ===== WORK & BUSINESS (30) =====
  ['trabajo', 'trabaho', 'work', 'A1', null],
  ['empleado', 'empleyado', 'work', 'A2', null],
  ['jefe', 'hepe', 'work', 'A2', 'Also means police chief.'],
  ['patrón', 'patron', 'work', 'B1', null],
  ['sueldo', 'sweldo', 'work', 'A2', null],
  ['salario', 'salaryo', 'work', 'B1', null],
  ['dinero', 'pera', 'work', 'A1', 'Pera from "pera/perra" (old Spanish coin).'],
  ['peso', 'piso', 'work', 'A1', 'Philippine currency.'],
  ['moneda', 'barya', 'work', 'A2', 'Barya from "barajar"? Actually from "varias".'],
  ['cambio', 'sukli', 'work', 'A2', 'Sukli native; kambiyo also used.'],
  ['cuenta', 'kwenta', 'work', 'A2', 'Also "count".'],
  ['banco', 'bangko', 'work', 'A1', null],
  ['tienda', 'tindahan', 'work', 'A1', 'Tindahan derives from Spanish via tinda.'],
  ['mercado', 'merkado', 'work', 'A1', null],
  ['precio', 'presyo', 'work', 'A1', null],
  ['barato', 'mura', 'work', 'A1', 'Mura native; barato used.'],
  ['empresa', 'empresa', 'work', 'B1', null],
  ['compañía', 'kumpanya', 'work', 'A2', null],
  ['negocio', 'negosyo', 'work', 'A2', null],
  ['contrato', 'kontrata', 'work', 'B1', null],
  ['contrata', 'kontrata', 'work', 'B1', null],
  ['firma', 'pirma', 'work', 'A2', 'Signature.'],
  ['factura', 'paktura', 'work', 'B1', null],
  ['recibo', 'resibo', 'work', 'A2', null],
  ['producto', 'produkto', 'work', 'A2', null],
  ['servicio', 'serbisyo', 'work', 'A2', null],
  ['cliente', 'kliyente', 'work', 'A2', null],
  ['vendedor', 'bendedor', 'work', 'B1', null],
  ['mercancía', 'merkansiya', 'work', 'B1', null],
  ['impuesto', 'buwis', 'work', 'B1', 'Buwis native.'],

  // ===== TIME (15) =====
  ['hora', 'oras', 'time', 'A1', null],
  ['minuto', 'minuto', 'time', 'A1', null],
  ['segundo', 'segundo', 'time', 'A1', null],
  ['día', 'araw', 'time', 'A1', 'Araw native.'],
  ['semana', 'linggo', 'time', 'A1', 'Linggo from domingo.'],
  ['mes', 'buwan', 'time', 'A1', 'Buwan native.'],
  ['año', 'taon', 'time', 'A1', 'Taon native; "anyo" used in formal.'],
  ['tiempo', 'tiyempo', 'time', 'A1', 'Also "weather".'],
  ['hoy', 'ngayon', 'time', 'A1', 'Ngayon native.'],
  ['mañana', 'umaga', 'time', 'A1', 'Umaga native; mañana as "tomorrow".'],
  ['ayer', 'kahapon', 'time', 'A1', 'Kahapon native.'],
  ['temprano', 'maaga', 'time', 'A2', 'Maaga native.'],
  ['tarde', 'hapon', 'time', 'A1', 'Afternoon; hapon native.'],
  ['noche', 'gabi', 'time', 'A1', 'Gabi native.'],
  ['reloj', 'relo', 'time', 'A1', null],

  // ===== PLACES & TRAVEL (30) =====
  ['ciudad', 'siyudad', 'places', 'A1', null],
  ['pueblo', 'bayan', 'places', 'A1', 'Bayan native.'],
  ['calle', 'kalye', 'places', 'A1', null],
  ['avenida', 'abenida', 'places', 'B1', null],
  ['plaza', 'plasa', 'places', 'A1', null],
  ['parque', 'parke', 'places', 'A1', null],
  ['iglesia', 'simbahan', 'places', 'A1', 'Simbahan from "simba" (to worship).'],
  ['hospital', 'ospital', 'places', 'A1', null],
  ['farmacia', 'parmasya', 'places', 'A2', null],
  ['restaurante', 'restawran', 'places', 'A1', null],
  ['hotel', 'otel', 'places', 'A1', null],
  ['aeropuerto', 'paliparan', 'places', 'A2', 'Paliparan native (from "lipad" = fly).'],
  ['estación', 'estasyon', 'places', 'A2', null],
  ['puerto', 'pwerto', 'places', 'A2', null],
  ['playa', 'dalampasigan', 'places', 'A1', 'Dalampasigan native; playa used.'],
  ['río', 'ilog', 'places', 'A1', 'Ilog native.'],
  ['montaña', 'bundok', 'places', 'A1', 'Bundok native.'],
  ['isla', 'isla', 'places', 'A1', null],
  ['país', 'bansa', 'places', 'A1', 'Bansa native.'],
  ['provincia', 'probinsya', 'places', 'A2', null],
  ['barrio', 'baryo', 'places', 'A2', null],
  ['calzada', 'kalsada', 'places', 'A1', 'Road.'],
  ['esquina', 'kanto', 'places', 'A2', 'Kanto from "canto".'],
  ['frontera', 'hanggahan', 'places', 'B1', 'Hanggahan native.'],
  ['capital', 'kabisera', 'places', 'A2', 'From Spanish "cabecera".'],
  ['cine', 'sine', 'places', 'A1', null],
  ['teatro', 'teatro', 'places', 'B1', null],
  ['museo', 'museo', 'places', 'B1', null],
  ['zoológico', 'sulogiko', 'places', 'B1', null],
  ['centro', 'sentro', 'places', 'A2', null],

  // ===== TRANSPORTATION (15) =====
  ['tren', 'tren', 'transport', 'A1', null],
  ['avión', 'eroplano', 'transport', 'A1', 'From "aeroplano".'],
  ['barco', 'barko', 'transport', 'A1', null],
  ['bicicleta', 'bisikleta', 'transport', 'A1', null],
  ['motocicleta', 'motorsiklo', 'transport', 'A2', null],
  ['coche', 'kotse', 'transport', 'A1', null],
  ['autobús', 'bus', 'transport', 'A1', null],
  ['taxi', 'taksi', 'transport', 'A1', null],
  ['camión', 'trak', 'transport', 'A2', 'Via English "truck"; kamyon also used.'],
  ['pasajero', 'pasahero', 'transport', 'A2', null],
  ['chofer', 'tsuper', 'transport', 'A2', null],
  ['pasaje', 'pasahe', 'transport', 'A2', 'Fare.'],
  ['boleto', 'tiket', 'transport', 'A1', 'Via English; also "boleta" used.'],
  ['gasolina', 'gasolina', 'transport', 'A1', null],
  ['llanta', 'goma', 'transport', 'A2', 'Goma from "goma" (rubber).'],

  // ===== RELIGION (25) =====
  ['iglesia', 'simbahan', 'religion', 'A1', null],
  ['Dios', 'Diyos', 'religion', 'A1', null],
  ['Jesús', 'Hesus', 'religion', 'A1', null],
  ['santo', 'santo', 'religion', 'A1', null],
  ['santa', 'santa', 'religion', 'A1', null],
  ['virgen', 'birhen', 'religion', 'A2', null],
  ['ángel', 'anghel', 'religion', 'A2', null],
  ['cielo', 'langit', 'religion', 'A2', 'Langit native; sielo used.'],
  ['alma', 'kaluluwa', 'religion', 'B1', 'Kaluluwa native.'],
  ['misa', 'misa', 'religion', 'A1', null],
  ['capilla', 'kapilya', 'religion', 'A2', null],
  ['padre', 'pari', 'religion', 'A1', 'Priest. Pari from "padre".'],
  ['altar', 'altar', 'religion', 'A2', null],
  ['rosario', 'rosaryo', 'religion', 'A2', null],
  ['cruz', 'krus', 'religion', 'A1', null],
  ['pascua', 'pasko', 'religion', 'A1', 'Christmas.'],
  ['fiesta', 'pista', 'religion', 'A1', 'Town fiesta.'],
  ['casamiento', 'kasal', 'religion', 'A2', 'Wedding. Kasal from "casar".'],
  ['confesar', 'kumpisal', 'religion', 'B1', null],
  ['comunión', 'komunyon', 'religion', 'B1', null],
  ['bautismo', 'binyag', 'religion', 'B1', 'Binyag from Malay/native.'],
  ['oración', 'dasal', 'religion', 'A2', 'Dasal from "rezar"? Actually native.'],
  ['campana', 'kampana', 'religion', 'A2', null],
  ['bendición', 'bendisyon', 'religion', 'B1', null],
  ['pecado', 'kasalanan', 'religion', 'B1', 'Kasalanan native; "pekado" also used.'],

  // ===== ANIMALS (15) =====
  ['caballo', 'kabayo', 'animals', 'A1', null],
  ['vaca', 'baka', 'animals', 'A1', null],
  ['perro', 'aso', 'animals', 'A1', 'Aso native; perro rare.'],
  ['gato', 'pusa', 'animals', 'A1', 'Pusa native; gato used in some regions.'],
  ['pájaro', 'ibon', 'animals', 'A1', 'Ibon native; paharo rare.'],
  ['pez', 'isda', 'animals', 'A1', 'Isda native.'],
  ['gallina', 'manok', 'animals', 'A1', 'Manok native; gallina rare.'],
  ['cerdo', 'baboy', 'animals', 'A1', 'Baboy native; puerko from "puerco" used.'],
  ['pato', 'pato', 'animals', 'A2', null],
  ['oveja', 'tupa', 'animals', 'A2', 'Tupa via Sanskrit-Malay.'],
  ['cabra', 'kambing', 'animals', 'A2', 'Kambing native.'],
  ['ratón', 'daga', 'animals', 'A2', 'Daga native.'],
  ['conejo', 'koneho', 'animals', 'A2', null],
  ['tigre', 'tigre', 'animals', 'B1', null],
  ['león', 'leon', 'animals', 'B1', null],

  // ===== NATURE & WEATHER (15) =====
  ['sol', 'araw', 'nature', 'A1', 'Araw native; "solar" used in compounds.'],
  ['luna', 'buwan', 'nature', 'A1', 'Buwan native.'],
  ['estrella', 'bituin', 'nature', 'A1', 'Bituin native.'],
  ['viento', 'hangin', 'nature', 'A1', 'Hangin native.'],
  ['lluvia', 'ulan', 'nature', 'A1', 'Ulan native.'],
  ['nube', 'ulap', 'nature', 'A1', 'Ulap native.'],
  ['fuego', 'apoy', 'nature', 'A1', 'Apoy native.'],
  ['agua', 'tubig', 'nature', 'A1', 'Tubig native; agua in compounds.'],
  ['tierra', 'lupa', 'nature', 'A1', 'Lupa native.'],
  ['flor', 'bulaklak', 'nature', 'A1', 'Bulaklak native; "por" rare.'],
  ['árbol', 'puno', 'nature', 'A1', 'Puno native.'],
  ['fruta', 'prutas', 'nature', 'A1', null],
  ['verano', 'tag-init', 'nature', 'A2', 'Tag-init native.'],
  ['invierno', 'tag-lamig', 'nature', 'A2', 'Tag-lamig native.'],
  ['tormenta', 'bagyo', 'nature', 'A2', 'Bagyo native; tormenta used.'],

  // ===== EMOTIONS & SOCIAL (20) =====
  ['amor', 'mahal', 'emotions', 'A2', 'Mahal native; amor used in songs.'],
  ['feliz', 'maligaya', 'emotions', 'A2', 'Maligaya native; pelis used rare.'],
  ['triste', 'malungkot', 'emotions', 'A2', 'Malungkot native.'],
  ['enojado', 'galit', 'emotions', 'A2', 'Galit native.'],
  ['contento', 'kontento', 'emotions', 'A2', null],
  ['nervioso', 'nerbyoso', 'emotions', 'A2', null],
  ['tranquilo', 'tranquilo', 'emotions', 'A2', null],
  ['loco', 'loko', 'emotions', 'A2', null],
  ['celoso', 'seloso', 'emotions', 'B1', null],
  ['orgulloso', 'mayabang', 'emotions', 'B1', 'Mayabang native.'],
  ['amigo', 'kaibigan', 'emotions', 'A1', 'Kaibigan native; amigo used.'],
  ['amiga', 'kaibigan', 'emotions', 'A1', null],
  ['señor', 'ginoo', 'emotions', 'A1', 'Ginoo native formal.'],
  ['señora', 'binibini', 'emotions', 'A1', 'Binibini native.'],
  ['señorita', 'binibini', 'emotions', 'A1', null],
  ['por favor', 'paki', 'emotions', 'A1', 'Paki native prefix.'],
  ['gracias', 'salamat', 'emotions', 'A1', 'Salamat from Arabic via Malay.'],
  ['perdón', 'pasensya', 'emotions', 'A1', 'Pasensya from "paciencia".'],
  ['hola', 'kumusta', 'emotions', 'A1', 'Kumusta from "¿Cómo está?".'],
  ['adiós', 'paalam', 'emotions', 'A1', 'Paalam native; adyos also used.'],

  // ===== VERBS — ADOPTED (40) =====
  ['cantar', 'kumanta', 'verbs', 'A1', null],
  ['bailar', 'magsayaw', 'verbs', 'A1', 'Sayaw native; "sumayaw" used.'],
  ['pasear', 'mamasyal', 'verbs', 'A2', null],
  ['esperar', 'mag-espera', 'verbs', 'A2', null],
  ['asistir', 'umasiste', 'verbs', 'B1', null],
  ['invitar', 'mag-imbita', 'verbs', 'A2', null],
  ['comparar', 'ikumpara', 'verbs', 'B1', null],
  ['festejar', 'magpista', 'verbs', 'B1', null],
  ['preparar', 'maghanda', 'verbs', 'A2', 'Handa native; "magprepara" also used.'],
  ['separar', 'hiwalayin', 'verbs', 'B1', 'Hiwalay native; "separa" used.'],
  ['contestar', 'sumagot', 'verbs', 'A2', 'Sagot native; "kontesta" also used.'],
  ['firmar', 'pumirma', 'verbs', 'A2', null],
  ['controlar', 'kontrolin', 'verbs', 'B1', null],
  ['considerar', 'isaalang-alang', 'verbs', 'B1', 'Native; "ikonsidera" also used.'],
  ['continuar', 'magpatuloy', 'verbs', 'A2', 'Patuloy native; "magkontinyu" rare.'],
  ['recordar', 'alalahanin', 'verbs', 'A2', 'Alala native; "rekordar" rare.'],
  ['organizar', 'ayusin', 'verbs', 'B1', 'Ayos native; "mag-organisa" used.'],
  ['participar', 'sumali', 'verbs', 'A2', 'Sali native; "mag-partisipa" used.'],
  ['decidir', 'magpasya', 'verbs', 'B1', 'Pasya native; "mag-desidi" used.'],
  ['estudiar', 'mag-aral', 'verbs', 'A1', 'Aral native.'],
  ['trabajar', 'magtrabaho', 'verbs', 'A1', null],
  ['viajar', 'maglakbay', 'verbs', 'A2', 'Lakbay native; "mamiyahe" from "viaje".'],
  ['pagar', 'magbayad', 'verbs', 'A1', 'Bayad native; "magpaga" rare.'],
  ['comprar', 'bumili', 'verbs', 'A1', 'Bili native; "kumomprar" rare.'],
  ['vender', 'magtinda', 'verbs', 'A1', 'Tinda related to tienda/vender.'],
  ['llamar', 'tumawag', 'verbs', 'A1', 'Tawag native; "lumyamada" rare.'],
  ['pasar', 'pumasa', 'verbs', 'A2', null],
  ['visitar', 'bumisita', 'verbs', 'A2', null],
  ['usar', 'gumamit', 'verbs', 'A1', 'Gamit native; "umusa" rare.'],
  ['crear', 'gumawa', 'verbs', 'A2', 'Gawa native.'],
  ['formar', 'bumuo', 'verbs', 'A2', 'Buo native.'],
  ['presentar', 'ipakilala', 'verbs', 'B1', null],
  ['acompañar', 'samahan', 'verbs', 'A2', 'Sama native; "akumpanya" used.'],
  ['aceptar', 'tanggapin', 'verbs', 'A2', 'Tanggap native; "asepta" used.'],
  ['recibir', 'tumanggap', 'verbs', 'A2', null],
  ['regalar', 'magregalo', 'verbs', 'A2', null],
  ['perdonar', 'magpatawad', 'verbs', 'B1', 'Patawad native; "magperdona" used.'],
  ['besar', 'humalik', 'verbs', 'A2', 'Halik native.'],
  ['abrazar', 'yakapin', 'verbs', 'A2', 'Yakap native.'],
  ['cocinar', 'magluto', 'verbs', 'A1', 'Luto native; "magkusina" used.'],

  // ===== ADJECTIVES (30) =====
  ['bueno', 'mabuti', 'adjectives', 'A1', 'Mabuti native; "bwena" in phrases.'],
  ['malo', 'masama', 'adjectives', 'A1', 'Masama native; "malo" rare.'],
  ['grande', 'malaki', 'adjectives', 'A1', 'Malaki native; "grande" in names.'],
  ['pequeño', 'maliit', 'adjectives', 'A1', 'Maliit native.'],
  ['alto', 'mataas', 'adjectives', 'A1', 'Mataas native; "alto" in music.'],
  ['bajo', 'mababa', 'adjectives', 'A1', 'Mababa native; "baho" for smell.'],
  ['largo', 'mahaba', 'adjectives', 'A1', 'Mahaba native.'],
  ['corto', 'maikli', 'adjectives', 'A1', 'Maikli native; "korto" = shorts.'],
  ['ancho', 'malapad', 'adjectives', 'A2', 'Malapad native; "antso" rare.'],
  ['estrecho', 'makitid', 'adjectives', 'A2', 'Makitid native.'],
  ['nuevo', 'bago', 'adjectives', 'A1', 'Bago native; "nwebo" rare.'],
  ['viejo', 'luma', 'adjectives', 'A1', 'Luma native (for things); "matanda" (for people).'],
  ['joven', 'bata', 'adjectives', 'A1', 'Bata native.'],
  ['rápido', 'mabilis', 'adjectives', 'A1', 'Mabilis native; "rapido" used.'],
  ['lento', 'mabagal', 'adjectives', 'A1', 'Mabagal native; "lento" in music.'],
  ['fácil', 'madali', 'adjectives', 'A1', 'Madali native; "pasil" from "fácil".'],
  ['difícil', 'mahirap', 'adjectives', 'A1', 'Mahirap native; "dipisil" used.'],
  ['bonito', 'maganda', 'adjectives', 'A1', 'Maganda native.'],
  ['feo', 'pangit', 'adjectives', 'A1', 'Pangit native.'],
  ['limpio', 'malinis', 'adjectives', 'A1', 'Malinis native.'],
  ['sucio', 'marumi', 'adjectives', 'A1', 'Marumi native.'],
  ['claro', 'malinaw', 'adjectives', 'A2', 'Malinaw native; "klaro" used.'],
  ['oscuro', 'madilim', 'adjectives', 'A2', 'Madilim native; "oskuro" used.'],
  ['fuerte', 'malakas', 'adjectives', 'A1', 'Malakas native.'],
  ['débil', 'mahina', 'adjectives', 'A1', 'Mahina native.'],
  ['lleno', 'puno', 'adjectives', 'A1', 'Puno native.'],
  ['vacío', 'walang laman', 'adjectives', 'A2', null],
  ['caliente', 'mainit', 'adjectives', 'A1', 'Mainit native; "kalyente" used.'],
  ['frío', 'malamig', 'adjectives', 'A1', 'Malamig native; "prio" rare.'],
  ['mismo', 'mismo', 'adjectives', 'A2', null],

  // ===== COMMON OBJECTS (25) =====
  ['puerta', 'pinto', 'objects', 'A1', null],
  ['silla', 'silya', 'objects', 'A1', null],
  ['mesa', 'mesa', 'objects', 'A1', null],
  ['lápiz', 'lapis', 'objects', 'A1', null],
  ['libro', 'libro', 'objects', 'A1', null],
  ['carta', 'karta', 'objects', 'A2', null],
  ['sobre', 'sobre', 'objects', 'A2', 'Envelope.'],
  ['bolsa', 'bag', 'objects', 'A1', 'Via English; "bolsa" also used.'],
  ['papel', 'papel', 'objects', 'A1', null],
  ['caja', 'kaha', 'objects', 'A1', null],
  ['llave', 'susi', 'objects', 'A2', 'Susi native; "llabi" rare.'],
  ['candado', 'kandado', 'objects', 'A2', null],
  ['máquina', 'makina', 'objects', 'A2', null],
  ['motor', 'motor', 'objects', 'A2', null],
  ['aguja', 'karayom', 'objects', 'A2', 'Karayom native.'],
  ['hilo', 'sinulid', 'objects', 'A2', 'Sinulid native; "ilo" in some.'],
  ['peine', 'suklay', 'objects', 'A2', 'Suklay native; "payne" used.'],
  ['cepillo', 'sepilyo', 'objects', 'A1', 'Toothbrush.'],
  ['jabón', 'sabon', 'objects', 'A1', null],
  ['espejo', 'salamin', 'objects', 'A1', 'Salamin native.'],
  ['toalla', 'tuwalya', 'objects', 'A1', null],
  ['paraguas', 'payong', 'objects', 'A1', 'Payong native; "paragwas" used.'],
  ['martillo', 'martilyo', 'objects', 'A2', null],
  ['clavo', 'pako', 'objects', 'A2', 'Pako native; "klabo" used.'],
  ['tornillo', 'turnilyo', 'objects', 'B1', null],

  // ===== MUSIC, ART, LEISURE (15) =====
  ['música', 'musika', 'music_art', 'A1', null],
  ['canción', 'kanta', 'music_art', 'A1', null],
  ['guitarra', 'gitara', 'music_art', 'A1', null],
  ['piano', 'piyano', 'music_art', 'A1', null],
  ['violín', 'biyolin', 'music_art', 'A2', null],
  ['tambor', 'tambol', 'music_art', 'A2', null],
  ['baile', 'sayaw', 'music_art', 'A1', 'Sayaw native.'],
  ['fiesta', 'pista', 'music_art', 'A1', null],
  ['teatro', 'teatro', 'music_art', 'B1', null],
  ['pintura', 'pintura', 'music_art', 'B1', null],
  ['foto', 'poto', 'music_art', 'A1', null],
  ['cámara', 'kamera', 'music_art', 'A2', null],
  ['película', 'pelikula', 'music_art', 'A1', null],
  ['actor', 'artista', 'music_art', 'A2', 'Artista also used for actor.'],
  ['artista', 'artista', 'music_art', 'A2', null],

  // ===== ADDITIONAL HIGH-FREQUENCY (25) =====
  ['general', 'heneral', 'general', 'B1', null],
  ['general', 'general', 'general', 'B1', null],
  ['especial', 'espesyal', 'general', 'A2', null],
  ['natural', 'natural', 'general', 'A2', null],
  ['normal', 'normal', 'general', 'A2', null],
  ['importante', 'importante', 'general', 'A2', null],
  ['necesario', 'kinakailangan', 'general', 'A2', 'Kinakailangan native; "nesesaryo" used.'],
  ['posible', 'posible', 'general', 'A2', null],
  ['imposible', 'imposible', 'general', 'A2', null],
  ['público', 'publiko', 'general', 'A2', null],
  ['privado', 'pribado', 'general', 'A2', null],
  ['nacional', 'nasyonal', 'general', 'B1', null],
  ['internacional', 'internasyonal', 'general', 'B1', null],
  ['local', 'lokal', 'general', 'A2', null],
  ['moderno', 'moderno', 'general', 'A2', null],
  ['antiguo', 'antigo', 'general', 'B1', null],
  ['moderno', 'moderno', 'general', 'A2', null],
  ['original', 'orihinal', 'general', 'A2', null],
  ['simple', 'simple', 'general', 'A2', null],
  ['diferente', 'iba', 'general', 'A1', 'Iba native; "diperente" used.'],
  ['mismo', 'pareho', 'general', 'A2', 'Pareho from "pareja".'],
  ['igual', 'pantay', 'general', 'A2', 'Pantay native; "igwal" used.'],
  ['grande', 'dakila', 'general', 'B1', 'Dakila native for "great".'],
  ['total', 'total', 'general', 'A2', null],
  ['número', 'numero', 'general', 'A1', null],

  // ===== PROFESSIONS (20) =====
  ['doctor', 'doktor', 'work', 'A1', null],
  ['enfermera', 'nars', 'work', 'A1', 'Nars via English "nurse".'],
  ['abogado', 'abogado', 'work', 'A2', null],
  ['ingeniero', 'inhinyero', 'work', 'A2', null],
  ['arquitecto', 'arkitekto', 'work', 'B1', null],
  ['policía', 'pulis', 'work', 'A1', null],
  ['soldado', 'sundalo', 'work', 'A2', null],
  ['bombero', 'bombero', 'work', 'A2', null],
  ['presidente', 'presidente', 'work', 'A1', null],
  ['alcalde', 'alkalde', 'work', 'A2', null],
  ['senador', 'senador', 'work', 'B1', null],
  ['gobernador', 'gobernador', 'work', 'B1', null],
  ['secretario', 'sekretarya', 'work', 'A2', null],
  ['contador', 'akawntant', 'work', 'A2', 'Via English.'],
  ['carpintero', 'karpintero', 'work', 'A2', null],
  ['mecánico', 'mekaniko', 'work', 'A2', null],
  ['panadero', 'panadero', 'work', 'A2', null],
  ['cocinero', 'kusinero', 'work', 'A1', null],
  ['camarero', 'weyter', 'work', 'A2', 'Via English "waiter".'],
  ['taxi', 'taksi', 'work', 'A1', null]
];

// Normalize to full object shape for INSERT
module.exports = COGNATES.map(([word_es, word_tl, category, cefr_level, etymology_note]) => ({
  word_es: word_es.trim(),
  word_tl: word_tl.trim(),
  category: category || 'general',
  cefr_level: cefr_level || 'A1',
  etymology_note: etymology_note || null,
  example_es: null,
  example_tl: null
}));
