'use strict';

// Generate a branded Digit2AI "Project Qualification Brief" PDF from a
// project's triage_structured output. Streams the PDF directly into an
// Express response — caller is the route handler.
//
// Why pdfkit (not puppeteer): pure Node, no headless Chrome to install,
// no Render cold-start penalty, deterministic output, ~100 KB per PDF.

const PDFDocument = require('pdfkit');
const { fetchWithTimeout } = require('./agents/fetchWithTimeout');

// Digit2AI brand colors (hex)
const COLOR_INK     = '#0f172a';
const COLOR_MUTED   = '#64748b';
const COLOR_ACCENT  = '#7c5cff'; // purple-blue gradient endpoint
const COLOR_ACCENT2 = '#22d3ee'; // cyan gradient endpoint
const COLOR_GO      = '#10b981';
const COLOR_WARN    = '#f59e0b';
const COLOR_STOP    = '#ef4444';

const LOGO_URL = 'https://assets.cdn.filesafe.space/3lSeAHXNU9t09Hhp9oai/media/69d97bc215a505b6793950c0.png';

// Cache the logo across requests so we don't refetch on every PDF.
// Cap at 200KB — bigger and we skip the embed and use a text header
// instead, otherwise every PDF balloons to 2+ MB which is awful for
// WhatsApp recipients on metered data.
const LOGO_MAX_BYTES = 200 * 1024;
let _logoBuf = null;
let _logoChecked = false;
async function getLogoBuffer() {
  if (_logoChecked) return _logoBuf;
  _logoChecked = true;
  try {
    const resp = await fetch(LOGO_URL);
    if (!resp.ok) return null;
    const ab = await resp.arrayBuffer();
    if (ab.byteLength > LOGO_MAX_BYTES) {
      console.warn(`[triagePdf] logo too large (${ab.byteLength} bytes) — using text header instead`);
      _logoBuf = null;
      return null;
    }
    _logoBuf = Buffer.from(ab);
    return _logoBuf;
  } catch (_) { return null; }
}

// Bilingual labels — picked at render time based on `lang` ('es' or 'en')
const L = {
  es: {
    title: 'Resumen de Calificación del Proyecto',
    generated: 'Generado',
    requestor: 'Solicitante',
    country: 'País',
    submitted: 'Enviado',
    summary: 'Resumen del Proyecto',
    fit: 'Calificación de Encaje',
    fitLabel: { accept: 'ACEPTAR', accept_with_conditions: 'Prueba de Concepto (PoC)', reject: 'RECHAZAR', review: 'REVISAR' },
    wedge: 'Cuña sugerida para v1',
    flags: 'Banderas regulatorias',
    synergies: 'Sinergias de portafolio',
    monetization: 'Opciones de monetización',
    competitors: 'Competidores a observar',
    questions: 'Preguntas para el stakeholder',
    questionsSub: 'Por favor responda estas preguntas en la próxima reunión, o por escrito a través del enlace seguro que recibió por correo.',
    page: 'Página',
    of: 'de',
    footer: 'Generado por Digit2AI Neural Intelligence · contacto: mstagg@digit2ai.com',
    severityHigh: 'ALTA',
    severityMedium: 'MEDIA',
    severityLow: 'BAJA'
  },
  en: {
    title: 'Project Qualification Brief',
    generated: 'Generated',
    requestor: 'Requestor',
    country: 'Country',
    submitted: 'Submitted',
    summary: 'Project Summary',
    fit: 'Fit Assessment',
    fitLabel: { accept: 'ACCEPT', accept_with_conditions: 'Proof of Concept (PoC)', reject: 'REJECT', review: 'REVIEW' },
    wedge: 'Suggested v1 Wedge',
    flags: 'Regulatory Flags',
    synergies: 'Portfolio Synergies',
    monetization: 'Monetization Options',
    competitors: 'Competitors to Watch',
    questions: 'Stakeholder Questions',
    questionsSub: 'Please answer these in the upcoming meeting, or in writing via the secure magic link you received by email.',
    page: 'Page',
    of: 'of',
    footer: 'Generated by Digit2AI Neural Intelligence · contact: mstagg@digit2ai.com',
    severityHigh: 'HIGH',
    severityMedium: 'MEDIUM',
    severityLow: 'LOW'
  }
};

function trafficColor(rec) {
  if (rec === 'accept') return COLOR_GO;
  if (rec === 'accept_with_conditions') return COLOR_WARN;
  if (rec === 'reject') return COLOR_STOP;
  return COLOR_MUTED;
}

// Pick questions array based on language; fall back to the other if missing.
function pickQuestions(s, lang) {
  if (!s) return [];
  if (lang === 'es') return Array.isArray(s.stakeholder_questions_es) && s.stakeholder_questions_es.length ? s.stakeholder_questions_es : (Array.isArray(s.stakeholder_questions_en) ? s.stakeholder_questions_en : []);
  return Array.isArray(s.stakeholder_questions_en) && s.stakeholder_questions_en.length ? s.stakeholder_questions_en : (Array.isArray(s.stakeholder_questions_es) ? s.stakeholder_questions_es : []);
}

function fmtDate(d, lang) {
  if (!d) return '';
  const dt = d instanceof Date ? d : new Date(d);
  return dt.toLocaleDateString(lang === 'es' ? 'es-ES' : 'en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}

// Add a footer + page number to every page. Called inside the doc.on('pageAdded')
// handler so it fires for the first page too.
function paintChrome(doc, lbl, total) {
  const w = doc.page.width;
  const h = doc.page.height;
  const margin = doc.page.margins.left;
  // Top accent bar (the brand gradient is awkward in PDFKit; use a flat stripe)
  doc.save();
  doc.rect(0, 0, w, 4).fill(COLOR_ACCENT);
  doc.restore();
  // Footer line + text — position absolute, doesn't disturb flow cursor
  const footerY = h - 36;
  doc.save();
  doc.strokeColor('#e2e8f0').lineWidth(0.5).moveTo(margin, footerY).lineTo(w - margin, footerY).stroke();
  doc.font('Helvetica').fontSize(8).fillColor(COLOR_MUTED);
  doc.text(lbl.footer, margin, footerY + 6, { width: w - margin * 2, align: 'left' });
  // Page N of M (we update after streaming via doc.switchToPage if needed,
  // but for v1 we just write the current number — Pages() requires keeping
  // a buffer in memory). Simple approach: just current page number.
  const pageStr = `${lbl.page} ${doc._pageBuffer ? doc._pageBuffer.length : ''}`;
  doc.text(`${doc.bufferedPageRange ? '' : ''}`, w - margin - 60, footerY + 6, { width: 60, align: 'right' });
  doc.restore();
}

// Section heading helper — colored bar + uppercase letterpaced label
function sectionHeading(doc, text) {
  doc.moveDown(0.6);
  const y = doc.y;
  doc.save();
  doc.rect(doc.page.margins.left, y, 3, 14).fill(COLOR_ACCENT);
  doc.restore();
  doc.font('Helvetica-Bold').fontSize(11).fillColor(COLOR_INK)
    .text(text.toUpperCase(), doc.page.margins.left + 10, y - 1, { characterSpacing: 0.8 });
  doc.moveDown(0.3);
  doc.font('Helvetica').fontSize(10).fillColor(COLOR_INK);
}

// Generate the PDF and pipe into the provided response.
// `res` is an Express response object. `lang` is 'es' or 'en'.
async function streamTriagePdf({ project, lang, res }) {
  const language = (lang === 'es' || lang === 'en') ? lang : 'en';
  const lbl = L[language];
  const s = project && project.triage_structured ? project.triage_structured : null;
  const questions = pickQuestions(s, language);

  const doc = new PDFDocument({
    size: 'LETTER',
    margins: { top: 60, bottom: 60, left: 60, right: 60 },
    bufferPages: true,
    info: {
      Title: `${lbl.title} — ${(project && project.name) || ''}`,
      Author: 'Digit2AI Neural Intelligence',
      Subject: lbl.title,
      CreationDate: new Date()
    }
  });

  // Stream content-type before piping (Express handles content-length via res.end)
  res.setHeader('Content-Type', 'application/pdf');
  const safeName = String((project && project.name) || 'project').replace(/[^\w\-]+/g, '_').slice(0, 80);
  res.setHeader('Content-Disposition', `inline; filename="qualification-brief-${safeName}.pdf"`);
  doc.pipe(res);

  // Logo (best-effort — pdf still renders if logo fetch fails or is too big)
  const logo = await getLogoBuffer();
  if (logo) {
    try {
      doc.image(logo, doc.page.margins.left, 30, { width: 140 });
      doc.moveDown(2.2);
    } catch (_) {
      // Logo render failed — fall through to text header
      doc.font('Helvetica-Bold').fontSize(18).fillColor(COLOR_ACCENT).text('Digit2AI', doc.page.margins.left, 32);
      doc.font('Helvetica').fontSize(9).fillColor(COLOR_MUTED).text('Neural Intelligence', doc.page.margins.left, 54);
      doc.moveDown(1.5);
    }
  } else {
    // No logo — render the wordmark as styled text so the header still looks branded
    doc.font('Helvetica-Bold').fontSize(18).fillColor(COLOR_ACCENT).text('Digit2AI', doc.page.margins.left, 32);
    doc.font('Helvetica').fontSize(9).fillColor(COLOR_MUTED).text('Neural Intelligence', doc.page.margins.left, 54);
    doc.moveDown(1.5);
  }

  // Title block
  doc.font('Helvetica-Bold').fontSize(22).fillColor(COLOR_INK).text(lbl.title);
  doc.font('Helvetica').fontSize(10).fillColor(COLOR_MUTED).text(`${lbl.generated}: ${fmtDate(new Date(), language)}`);
  doc.moveDown(0.4);
  doc.font('Helvetica-Bold').fontSize(15).fillColor(COLOR_INK).text(project.name || '');

  // Project meta line
  const submittedDate = project.created_at ? fmtDate(project.created_at, language) : '';
  const metaParts = [];
  if (project.submitter_name || project.submitter_email) metaParts.push(`${lbl.requestor}: ${project.submitter_name || project.submitter_email}`);
  if (project.country) metaParts.push(`${lbl.country}: ${project.country}`);
  if (submittedDate) metaParts.push(`${lbl.submitted}: ${submittedDate}`);
  if (metaParts.length) {
    doc.moveDown(0.3);
    doc.font('Helvetica').fontSize(10).fillColor(COLOR_MUTED).text(metaParts.join('  ·  '));
  }

  // Fit assessment + traffic light (if structured exists)
  if (s) {
    doc.moveDown(0.8);
    const recRaw = s.go_no_go_recommendation || 'review';
    const fit = (typeof s.fit_score !== 'undefined' && s.fit_score !== null) ? Number(s.fit_score) : null;
    const tc = trafficColor(recRaw);
    const recLabel = lbl.fitLabel[recRaw] || lbl.fitLabel.review;
    // Background pill
    const startY = doc.y;
    const pillH = 36;
    doc.save();
    doc.roundedRect(doc.page.margins.left, startY, doc.page.width - doc.page.margins.left - doc.page.margins.right, pillH, 6)
       .fillOpacity(0.10).fill(tc).fillOpacity(1);
    doc.restore();
    // Label + score
    doc.font('Helvetica-Bold').fontSize(11).fillColor(tc)
       .text(`${lbl.fit}: ${recLabel}${fit !== null ? '  ·  ' + fit + '/10' : ''}`, doc.page.margins.left + 12, startY + 11);
    doc.y = startY + pillH + 6;
    doc.fillColor(COLOR_INK);

    if (s.fit_reasoning) {
      doc.moveDown(0.4);
      doc.font('Helvetica').fontSize(10).fillColor(COLOR_INK).text(String(s.fit_reasoning), { align: 'left' });
    }

    if (s.wedge_recommendation) {
      sectionHeading(doc, lbl.wedge);
      doc.text(String(s.wedge_recommendation), { align: 'left' });
    }
  }

  // Project submitted summary
  if (project.description) {
    sectionHeading(doc, lbl.summary);
    const desc = String(project.description).slice(0, 1200);
    doc.text(desc, { align: 'left' });
  }

  // Regulatory flags
  if (s && Array.isArray(s.regulatory_flags) && s.regulatory_flags.length) {
    sectionHeading(doc, lbl.flags);
    s.regulatory_flags.forEach(f => {
      const sev = String(f.severity || 'medium').toLowerCase();
      const sevLabel = sev === 'high' ? lbl.severityHigh : sev === 'low' ? lbl.severityLow : lbl.severityMedium;
      const sevColor = sev === 'high' ? COLOR_STOP : sev === 'low' ? COLOR_MUTED : COLOR_WARN;
      doc.font('Helvetica-Bold').fontSize(10).fillColor(sevColor).text(`[${sevLabel}] `, { continued: true });
      doc.font('Helvetica-Bold').fillColor(COLOR_INK).text(String(f.risk || ''), { continued: true });
      if (f.what_to_check) {
        doc.font('Helvetica').fillColor(COLOR_MUTED).text(` — ${f.what_to_check}`);
      } else {
        doc.text('');
      }
      doc.moveDown(0.2);
    });
  }

  // Portfolio synergies
  if (s && Array.isArray(s.portfolio_synergies) && s.portfolio_synergies.length) {
    sectionHeading(doc, lbl.synergies);
    s.portfolio_synergies.forEach(p => {
      doc.font('Helvetica-Bold').fillColor(COLOR_INK).text(`• ${p.product || ''}`, { continued: true });
      if (p.angle) doc.font('Helvetica').fillColor(COLOR_MUTED).text(` — ${p.angle}`);
      else doc.text('');
      doc.moveDown(0.15);
    });
  }

  // Monetization options
  if (s && Array.isArray(s.monetization_options) && s.monetization_options.length) {
    sectionHeading(doc, lbl.monetization);
    s.monetization_options.forEach(m => {
      doc.font('Helvetica').fillColor(COLOR_INK).text(`• ${m}`);
      doc.moveDown(0.1);
    });
  }

  // Competitors to watch
  if (s && Array.isArray(s.competitors_to_watch) && s.competitors_to_watch.length) {
    sectionHeading(doc, lbl.competitors);
    s.competitors_to_watch.forEach(c => {
      doc.font('Helvetica').fillColor(COLOR_INK).text(`• ${c}`);
      doc.moveDown(0.1);
    });
  }

  // Stakeholder questions (the headline of the document)
  if (questions.length) {
    // Force a clean page break if we're past 75% of the current page to
    // avoid the heading being orphaned at the bottom.
    if (doc.y > doc.page.height - 220) doc.addPage();
    sectionHeading(doc, lbl.questions);
    doc.font('Helvetica-Oblique').fontSize(9).fillColor(COLOR_MUTED).text(lbl.questionsSub);
    doc.moveDown(0.6);
    questions.forEach((q, i) => {
      // Each question: numbered, bold question, plenty of white space below
      // so the recipient could write a handwritten answer if they printed it.
      doc.font('Helvetica-Bold').fontSize(11).fillColor(COLOR_INK).text(`${i + 1}. `, { continued: true });
      doc.font('Helvetica').fillColor(COLOR_INK).text(String(q));
      doc.moveDown(0.3);
      // Answer space — three thin lines so the page works as a fillable handout
      const ansY = doc.y;
      const lineW = doc.page.width - doc.page.margins.left - doc.page.margins.right;
      for (let li = 0; li < 3; li++) {
        const y = ansY + li * 14;
        doc.save();
        doc.strokeColor('#cbd5e1').lineWidth(0.5).moveTo(doc.page.margins.left, y).lineTo(doc.page.margins.left + lineW, y).stroke();
        doc.restore();
      }
      doc.y = ansY + 3 * 14 + 8;
      // Force a page break if the next question wouldn't fit
      if (doc.y > doc.page.height - 160 && i < questions.length - 1) doc.addPage();
    });
  }

  // Paint footer on every page (chrome) — pdfkit lets us walk buffered pages.
  //
  // CRITICAL: footer text positions at y = page.height - 30, which is BELOW the
  // bottom margin (margin.bottom = 60). pdfkit's text() auto-pages whenever the
  // cursor lands outside the writable area. Two text() calls per page × N pages
  // silently inflated the PDF by 2N blank chrome-only pages (prod: 5 real pages
  // -> 15 total). Workaround: zero margins.bottom while painting the footer so
  // the cursor stays inside the "writable" zone (the brief window covers both
  // text() calls per page; lineBreak:false is belt-and-suspenders).
  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(range.start + i);
    // Top accent stripe
    doc.save();
    doc.rect(0, 0, doc.page.width, 4).fill(COLOR_ACCENT);
    doc.restore();
    // Footer line + text
    const fw = doc.page.width;
    const fh = doc.page.height;
    const fm = doc.page.margins.left;
    const fy = fh - 36;
    const savedBottom = doc.page.margins.bottom;
    doc.page.margins.bottom = 0;
    try {
      doc.save();
      doc.strokeColor('#e2e8f0').lineWidth(0.5).moveTo(fm, fy).lineTo(fw - fm, fy).stroke();
      doc.font('Helvetica').fontSize(8).fillColor(COLOR_MUTED);
      doc.text(lbl.footer, fm, fy + 6, { width: fw - fm * 2 - 80, align: 'left', lineBreak: false });
      doc.text(`${lbl.page} ${i + 1} ${lbl.of} ${range.count}`, fw - fm - 80, fy + 6, { width: 80, align: 'right', lineBreak: false });
      doc.restore();
    } finally {
      doc.page.margins.bottom = savedBottom;
    }
  }

  doc.end();
}

module.exports = { streamTriagePdf };
