import React, { useState, useEffect } from 'react';
import api from '../services/api';
export default function Compliance() {
  const [records, setRecords] = useState([]);
  const [dot, setDot] = useState('');
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  useEffect(()=>{loadR();}, []);
  const loadR = async () => { const {data}=await api.get('/fmcsa/compliance').catch(()=>({data:{data:[]}})); setRecords(data?.data||[]); };
  const verify = async (e) => { e.preventDefault(); setLoading(true); try { const {data}=await api.post('/fmcsa/verify',{dot_number:dot}); setResult(data.data); loadR(); } catch(e){alert(e.response?.data?.error||'Failed');} setLoading(false); };
  const rc = {LOW:'#10B981',MEDIUM:'#F59E0B',HIGH:'#EF4444'};
  const stc = {AUTHORIZED:'#10B981','NOT AUTHORIZED':'#EF4444',UNKNOWN:'#8B949E'};
  return (<div>
    <h1 style={S.title}>FMCSA COMPLIANCE ENGINE</h1>
    <div style={S.lc}><h3 style={S.ft}>Carrier Authority Lookup</h3><form onSubmit={verify} style={{display:'flex',gap:10,flexWrap:'wrap'}}><input style={S.input} placeholder="DOT Number" value={dot} onChange={e=>setDot(e.target.value)} required /><button style={S.btn} type="submit" disabled={loading}>{loading?'Checking...':'Verify Authority'}</button></form>
    {result&&<div style={S.rc}><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:16}}><div><div style={{fontSize:18,fontWeight:600}}>{result.legal_name||'Unknown'}</div><div style={{fontSize:12,color:'#8B949E'}}>DOT# {result.dot_number}</div></div><div style={{padding:'4px 12px',borderRadius:8,fontSize:12,fontWeight:700,letterSpacing:1,background:(rc[result.risk_level]||'#8B949E')+'22',color:rc[result.risk_level]||'#8B949E'}}>{result.risk_level} RISK</div></div><div style={S.rg}><div><span style={S.rl}>Status:</span> <span style={{color:stc[result.operating_status]||'#8B949E',fontWeight:600}}>{result.operating_status}</span></div><div><span style={S.rl}>Safety:</span> {result.safety_rating||'Not Rated'}</div><div><span style={S.rl}>Units:</span> {result.power_units||'-'}</div><div><span style={S.rl}>Drivers:</span> {result.drivers||'-'}</div></div><div style={{padding:'8px 12px',background:'#161B22',borderRadius:6,fontSize:13,borderLeft:'3px solid #0EA5E9',marginTop:12}}>{result.recommendation}</div></div>}</div>
    <h2 style={{fontFamily:"'Bebas Neue',sans-serif",fontSize:20,marginBottom:12}}>COMPLIANCE RECORDS</h2>
    <div style={S.tw}><table style={S.table}><thead><tr><th style={S.th}>DOT#</th><th style={S.th}>NAME</th><th style={S.th}>STATUS</th><th style={S.th}>SAFETY</th><th style={S.th}>ONBOARDING</th><th style={S.th}>LAST CHECK</th></tr></thead><tbody>{records.map(r=>(<tr key={r.id} style={S.tr}><td style={S.td}>{r.dot_number}</td><td style={S.td}>{r.legal_name}</td><td style={S.td}><span style={{color:stc[r.operating_status]||'#8B949E',fontWeight:600}}>{r.operating_status}</span></td><td style={S.td}>{r.safety_rating||'-'}</td><td style={S.td}><span style={{padding:'3px 8px',borderRadius:10,fontSize:10,fontWeight:600,background:r.onboarding_status==='approved'?'#10B98122':'#F59E0B22',color:r.onboarding_status==='approved'?'#10B981':'#F59E0B'}}>{r.onboarding_status}</span></td><td style={S.td}>{r.last_fmcsa_check?new Date(r.last_fmcsa_check).toLocaleDateString():'-'}</td></tr>))}{records.length===0&&<tr><td colSpan={6} style={{...S.td,textAlign:'center',color:'#8B949E'}}>No records</td></tr>}</tbody></table></div>
  </div>);
}
const S={title:{fontFamily:"'Bebas Neue',sans-serif",fontSize:28,color:'#0EA5E9',letterSpacing:2,marginBottom:16},lc:{background:'#161B22',border:'1px solid #21262D',borderRadius:10,padding:24,marginBottom:24},ft:{fontFamily:"'Bebas Neue',sans-serif",fontSize:20,color:'#E6EDF3',marginBottom:12},input:{padding:'10px 14px',background:'#0D1117',border:'1px solid #30363D',borderRadius:6,color:'#E6EDF3',fontSize:14,outline:'none',minWidth:200},btn:{padding:'10px 20px',background:'#0EA5E9',color:'#fff',border:'none',borderRadius:6,fontSize:14,fontWeight:600,cursor:'pointer'},rc:{marginTop:16,padding:20,background:'#0D1117',borderRadius:8,border:'1px solid #21262D'},rg:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(200px,1fr))',gap:10},rl:{fontSize:11,color:'#8B949E'},tw:{background:'#161B22',border:'1px solid #21262D',borderRadius:10,overflow:'auto'},table:{width:'100%',borderCollapse:'collapse',minWidth:600},th:{padding:'12px 14px',textAlign:'left',fontSize:11,color:'#8B949E',fontWeight:600,letterSpacing:1,borderBottom:'1px solid #21262D'},tr:{borderBottom:'1px solid #21262D'},td:{padding:'10px 14px',fontSize:13}};
