import React, { useState, useEffect } from 'react';
import api from '../services/api';
export default function ShipperPortal() {
  const [tab, setTab] = useState('shipments');
  const [shipments, setShipments] = useState([]);
  const [quotes, setQuotes] = useState([]);
  const [qf, setQf] = useState({ origin: '', destination: '', freight_type: 'General', weight_lbs: '', pickup_date: '' });
  const [qr, setQr] = useState(null);
  const [loading, setLoading] = useState(false);
  useEffect(() => { load(); }, []);
  const load = async () => {
    const [s1, s2] = await Promise.all([api.get('/shipper/shipments').catch(()=>({data:{data:[]}})), api.get('/shipper/quotes').catch(()=>({data:{data:[]}}))]);
    setShipments(s1.data?.data||[]); setQuotes(s2.data?.data||[]);
  };
  const requestQuote = async (e) => {
    e.preventDefault(); setLoading(true);
    try { const {data} = await api.post('/tools/call', {tool:'request_quote',input:qf}); setQr(data.result); load(); } catch(err) { alert(err.response?.data?.error||'Failed'); }
    setLoading(false);
  };
  const book = async (id) => { try { await api.post('/tools/call',{tool:'submit_booking',input:{quote_id:id}}); alert('Booked!'); setQr(null); load(); } catch(e){alert(e.response?.data?.error||'Failed');} };
  const sc = {open:'#0EA5E9',covered:'#F59E0B',in_transit:'#A855F7',delivered:'#10B981'};
  return (<div>
    <h1 style={S.title}>SHIPPER PORTAL</h1>
    <div style={S.tabs}>{['shipments','quote','quotes'].map(t=>(<button key={t} onClick={()=>setTab(t)} style={tab===t?S.tabA:S.tab}>{t==='quote'?'New Quote':t.charAt(0).toUpperCase()+t.slice(1)}</button>))}</div>
    {tab==='shipments'&&<div style={S.tw}><table style={S.table}><thead><tr><th style={S.th}>REF</th><th style={S.th}>ORIGIN</th><th style={S.th}>DEST</th><th style={S.th}>STATUS</th><th style={S.th}>RATE</th><th style={S.th}>PICKUP</th></tr></thead><tbody>{shipments.map(l=>(<tr key={l.id} style={S.tr}><td style={S.td}>{l.load_ref}</td><td style={S.td}>{l.origin}</td><td style={S.td}>{l.destination}</td><td style={S.td}><span style={{...S.badge,background:(sc[l.status]||'#8B949E')+'22',color:sc[l.status]||'#8B949E'}}>{l.status}</span></td><td style={S.td}>${l.shipper_rate||l.rate_usd||'-'}</td><td style={S.td}>{l.pickup_date||'-'}</td></tr>))}{shipments.length===0&&<tr><td colSpan={6} style={{...S.td,textAlign:'center',color:'#8B949E'}}>No shipments</td></tr>}</tbody></table></div>}
    {tab==='quote'&&<div style={S.fc}><h3 style={S.ft}>Request a Freight Quote</h3><form onSubmit={requestQuote}><div style={S.fg}><input style={S.input} placeholder="Origin" value={qf.origin} onChange={e=>setQf({...qf,origin:e.target.value})} required /><input style={S.input} placeholder="Destination" value={qf.destination} onChange={e=>setQf({...qf,destination:e.target.value})} required /><select style={S.input} value={qf.freight_type} onChange={e=>setQf({...qf,freight_type:e.target.value})}><option>General</option><option>Refrigerated</option><option>Flatbed</option><option>Hazmat</option></select><input style={S.input} type="number" placeholder="Weight (lbs)" value={qf.weight_lbs} onChange={e=>setQf({...qf,weight_lbs:e.target.value})} /><input style={S.input} type="date" value={qf.pickup_date} onChange={e=>setQf({...qf,pickup_date:e.target.value})} /></div><button style={S.btn} type="submit" disabled={loading}>{loading?'Getting AI Quote...':'Get Instant Quote'}</button></form>{qr&&<div style={S.qr}><h3 style={{fontFamily:"'Bebas Neue',sans-serif",fontSize:20,color:'#10B981',marginBottom:12}}>Quote #{qr.quote_id}</h3><div style={S.qg}><div><span style={S.ql}>Rate:</span> <strong style={{color:'#10B981',fontSize:24}}>${qr.quoted_rate}</strong></div><div><span style={S.ql}>Per Mile:</span> ${qr.rate_per_mile}</div><div><span style={S.ql}>Distance:</span> ~{qr.estimated_miles}mi</div><div><span style={S.ql}>Method:</span> {qr.pricing_method}</div></div><button style={{...S.btn,background:'#10B981',marginTop:12}} onClick={()=>book(qr.quote_id)}>Book This Shipment</button></div>}</div>}
    {tab==='quotes'&&<div style={S.tw}><table style={S.table}><thead><tr><th style={S.th}>ID</th><th style={S.th}>LANE</th><th style={S.th}>RATE</th><th style={S.th}>STATUS</th><th style={S.th}>ACTION</th></tr></thead><tbody>{quotes.map(q=>(<tr key={q.id} style={S.tr}><td style={S.td}>#{q.id}</td><td style={S.td}>{q.origin} → {q.destination}</td><td style={S.td}>${q.quoted_rate}</td><td style={S.td}><span style={S.badge}>{q.status}</span></td><td style={S.td}>{q.status==='quoted'&&<button style={S.sm} onClick={()=>book(q.id)}>Book</button>}</td></tr>))}</tbody></table></div>}
  </div>);
}
const S={title:{fontFamily:"'Bebas Neue',sans-serif",fontSize:28,color:'#0EA5E9',letterSpacing:2,marginBottom:16},tabs:{display:'flex',gap:8,marginBottom:20,flexWrap:'wrap'},tab:{padding:'8px 16px',background:'none',border:'1px solid #30363D',color:'#8B949E',borderRadius:6,cursor:'pointer',fontSize:13},tabA:{padding:'8px 16px',background:'#0EA5E922',border:'1px solid #0EA5E9',color:'#0EA5E9',borderRadius:6,cursor:'pointer',fontSize:13,fontWeight:600},tw:{background:'#161B22',border:'1px solid #21262D',borderRadius:10,overflow:'auto'},table:{width:'100%',borderCollapse:'collapse',minWidth:600},th:{padding:'12px 14px',textAlign:'left',fontSize:11,color:'#8B949E',fontWeight:600,letterSpacing:1,borderBottom:'1px solid #21262D'},tr:{borderBottom:'1px solid #21262D'},td:{padding:'10px 14px',fontSize:13},badge:{padding:'3px 8px',borderRadius:10,fontSize:11,fontWeight:600,textTransform:'uppercase',background:'#30363D',color:'#8B949E'},fc:{background:'#161B22',border:'1px solid #21262D',borderRadius:10,padding:24},ft:{fontFamily:"'Bebas Neue',sans-serif",fontSize:20,color:'#E6EDF3',marginBottom:16},fg:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(200px,1fr))',gap:12,marginBottom:16},input:{width:'100%',padding:'10px 12px',background:'#0D1117',border:'1px solid #30363D',borderRadius:6,color:'#E6EDF3',fontSize:13,outline:'none'},btn:{padding:'10px 24px',background:'#0EA5E9',color:'#fff',border:'none',borderRadius:6,fontSize:14,fontWeight:600,cursor:'pointer'},sm:{padding:'4px 10px',background:'#10B981',color:'#fff',border:'none',borderRadius:4,fontSize:11,cursor:'pointer'},qr:{marginTop:20,padding:20,background:'#0D1117',border:'1px solid #10B981',borderRadius:10},qg:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:12},ql:{fontSize:11,color:'#8B949E'}};
